/**
 * ShowAllRouterViewsPlugin — dashboard-transform plugin that surfaces
 * every configured routing rule on the Manifest routing page so the
 * operator can audit stale rules (header tiers pointing to deleted
 * providers, specificity assignments that are `is_active: false`,
 * complexity tier overrides for models the agent no longer has
 * credentials for, etc.) and clean them up.
 *
 * Background: as of commit `49ef687` (Manifest 6.x), the upstream
 * routing page (`packages/frontend/src/pages/Routing.tsx`) applies a
 * "deprecation gate" that hides both the **Complexity** and the
 * **Task-specific** routing surfaces from agents that have never
 * configured them. The gate is sticky per session
 * (`legacyComplexityVisible` + `legacySpecificityVisible` createSignals),
 * and the **Custom** (header-tier) surface is gated separately by a
 * per-tier `enabled` flag.
 *
 * Concretely, the upstream gate means a clean agent only sees the
 * `Default` and `Custom` tabs; the `Complexity` (simple / standard /
 * complex / reasoning) and `Task-specific` (coding / trading / image
 * gen / etc.) sections never render — even if database rows exist for
 * them.
 *
 * ## How this plugin surfaces the missing rules
 *
 * The plugin takes a **strictly additive** approach: it never mutates
 * the existing DOM, never injects CSS, and never runs a
 * MutationObserver against the page. The upstream gate uses SolidJS
 * `<Show when={false}>` guards which don't render the children at all,
 * so trying to "force show" them via `display: revert !important` is
 * both futile (no DOM to target) and harmful (it breaks the existing
 * flex/grid layouts of the routing cards that ARE rendered).
 *
 * Instead, the plugin ONLY adds a NEW collapsible panel above the
 * existing `.routing-tabs` element. The panel:
 *
 *   1. Detects the routing page (URL pattern
 *      `/(agents|harnesses)/<name>/routing`).
*   2. Fetches every routing surface via the public API in parallel:
*      - `/api/v1/routing/<name>/tiers`              (all 5 rows: default + 4 stages)
*      - `/api/v1/routing/<name>/specificity`         (every category)
*      - `/api/v1/routing/<name>/header-tiers`        (every row, including disabled)
*      - `/api/v1/routing/<name>/complexity/status`   (whether complexity is enabled)
*   3. Renders the fetched data as three flat read-only tables in
*      the panel — including the 4 complexity-tier rows
*      (simple/standard/complex/reasoning) the upstream UI hides via
*      the deprecation gate.
*   4. Includes a `Complexity routing status` footer with a single
*      `Disable / Enable complexity routing` button. This is the
*      OFFICIAL, upstream-blessed fix for the operator's "calls
*      accidentally route to simple" problem — per
*      `packages/backend/src/routing/routing-core/resolve.service.ts`,
*      when complexity_routing_enabled = false, every request
*      short-circuits to the `default` tier. There is no upstream
*      endpoint to delete the auto-created tier rows themselves;
*      this toggle is the only operator-controllable lever.
*
* The panel is read-only: no Delete buttons (they would either
* no-op on rows without overrides, or hit upstream
* `assertStreamableResponseMode` validation bugs on stream-mode
* tiers without stream-capable fallbacks). For per-row edits the
* operator uses the dashboard's existing UI; this plugin only
* surfaces the data the deprecation gate hides.
*
* The panel is collapsed by default (one-line summary: `N rules: 2 tier
* overrides, 1 specificity, 1 header tier`). Clicking the panel
* header (or the `Show all / Hide` button) expands the full tables
* inline. Keyboard-accessible (Enter / Space toggle the panel).
 *
 * ## Toggle-off contract
 *
 * When the operator disables the plugin via the admin UI:
 *   - The next request to `/admin/dashboard-transform/all.js` omits
 *     this plugin's IIFE (the bundle is built per-request from
 *     enabled plugins).
 *   - The operator refreshes the routing page; the new bundle has no
 *     `show-all-router-views` IIFE; no panel renders; zero side
 *     effects remain.
 * The plugin does NOT ship a runtime "kill switch" because the
 * dashboard-transform bundle is reloaded on every page navigation
 * (no caching headers), so a refresh is sufficient. The MutationObserver
 * on `document.body` is bounded to `childList + subtree` only (no
 * `attributes` filter) so it has negligible runtime cost.
 *
 * ## Why not un-hide the upstream tabs?
 *
 * We could patch the upstream `Routing.tsx` source to remove the
 * `<Show when={legacyComplexityVisible()}>` guard. That would un-hide
 * the tabs without changing semantics. We deliberately do NOT do that
 * here because:
 *   - Source-patching upstream files is brittle (every Manifest
 *     release reverts the patch, breaking the audit surface).
 *   - The audit panel approach is independent of the upstream
 *     deprecation strategy; even if upstream renames the signals or
 *     re-hides the tabs under a different mechanism, this plugin
 *     still surfaces every configured rule via the public API.
 *   - The user explicitly asked for "just adding more views/panels",
 *     not modifying the existing ones.
 *
 * ## Plugin kind
 *
 * `dashboard-transform`. This is a new kind introduced by this plugin;
 * the host walks the registry, collects `getDashboardScript()` output
 * from every enabled `dashboard-transform` plugin, and the dashboard
 * mount overlay injects a single combined `<script>` tag that loads
 * them. See `src/index.ts` for the kind enum and the admin server's
 * `/admin/dashboard-transform/all.js` route.
 */
import type {
  DashboardTransformPlugin,
  PluginKind,
  PluginMetadata,
} from '../..';

export const SHOW_ALL_ROUTER_VIEWS_PLUGIN_KIND: PluginKind = 'dashboard-transform';

export const SHOW_ALL_ROUTER_VIEWS_PLUGIN_METADATA: PluginMetadata = Object.freeze({
  id: 'show-all-router-views',
  name: 'Show all router views',
  version: '0.1.0',
  description:
    'Un-hides the Complexity and Task-specific routing tabs on the ' +
    'Manifest routing page and adds a "Reveal all routing views" panel ' +
    'that lists every configured routing rule (including stale ones the ' +
    'upstream UI hides via the deprecation gate). Use it to audit and ' +
    'clean up header tiers, specificity assignments, and complexity ' +
    'tier overrides that are still routing but no longer visible in ' +
    'the dashboard.',
  kind: SHOW_ALL_ROUTER_VIEWS_PLUGIN_KIND,
});

/**
 * The browser-side script that the admin server concatenates into
 * `/admin/dashboard-transform/all.js` for every enabled
 * `dashboard-transform` plugin.
 *
 * Shape: an IIFE that registers one entry on `window.__manifestPluginsDashboardTransform`.
 * The single combined bundle iterates that registry on `DOMContentLoaded`
 * and runs each entry. This shape lets the host's load order stay
 * stable regardless of how many `dashboard-transform` plugins are
 * installed, and lets each plugin's script fail independently (one
 * broken plugin does not abort the others).
 *
 * Source of truth: this constant. Authoring the JS inline (rather
 * than shipping a separate `.js` file and bundling it with esbuild)
 * keeps the plugin's runtime shape inside the TypeScript type system
 * so plugin authors get autocomplete and the build catches syntax
 * errors at compile time.
 *
 * Minification: the admin server does NOT minify the bundle. The
 * total payload across all plugins is well under the 16KB gzip
 * threshold for above-the-fold scripts, and unminified output makes
 * it trivial to debug from the browser devtools ("which plugin
 * emitted this line?").
 */
export const SHOW_ALL_ROUTER_VIEWS_SCRIPT: string = [
  '(function () {',
  '  \'use strict\';',
  '  if (typeof window === \'undefined\') return;',
  '',
  '  if (window.__manifestPluginsDashboardTransform === undefined) {',
  '    window.__manifestPluginsDashboardTransform = [];',
  '  }',
  '  if (window.__manifestPluginsDashboardTransform.some(function (e) { return e.id === \'show-all-router-views\'; })) {',
  '    return;',
  '  }',
  '',
  '  var PLUGIN_ID = \'show-all-router-views\';',
  '  var SCRIPT_VERSION = \'0.1.0\';',
  '',
  '  // The routing page URL pattern. Captures the agent name (URL-decoded by the server before any fetch).',
  '  // The Manifest routing page URL changed across releases: pre-harness-rename',
  '  // builds use /agents/<name>/routing; newer builds (post the agents→harnesses',
  '  // rename) use /harnesses/<name>/routing. Match both so the plugin fires on',
  '  // every Manifest version. The capture group is still the entity name.',
  '  var ROUTING_PATH_RE = /^\\/(?:agents|harnesses)\\/([^/]+)\\/routing\\/?$/;',
  '',
  '  function el(tag, attrs, children) {',
  '    var node = document.createElement(tag);',
  '    if (attrs) {',
  '      for (var k in attrs) {',
  '        if (Object.prototype.hasOwnProperty.call(attrs, k)) {',
  '          var v = attrs[k];',
  '          if (v === null || v === undefined || v === false) continue;',
  '          if (k === \'class\') node.className = v;',
  '          else if (k === \'style\' && typeof v === \'object\') {',
  '            for (var sk in v) {',
  '              if (Object.prototype.hasOwnProperty.call(v, sk)) {',
  '                node.style[sk] = v[sk];',
  '              }',
  '            }',
  '          } else if (k.indexOf(\'on\') === 0 && typeof v === \'function\') {',
  '            node.addEventListener(k.slice(2).toLowerCase(), v);',
  '          } else if (k === \'dataset\' && typeof v === \'object\') {',
  '            for (var dk in v) {',
  '              if (Object.prototype.hasOwnProperty.call(v, dk)) {',
  '                node.dataset[dk] = v[dk];',
  '              }',
  '            }',
  '          } else {',
  '            node.setAttribute(k, v === true ? \'\' : String(v));',
  '          }',
  '        }',
  '      }',
  '    }',
  '    if (children !== undefined && children !== null) {',
  '      if (!Array.isArray(children)) children = [children];',
  '      for (var i = 0; i < children.length; i += 1) {',
  '        var c = children[i];',
  '        if (c === null || c === undefined || c === false) continue;',
  '        if (typeof c === \'string\' || typeof c === \'number\') {',
  '          node.appendChild(document.createTextNode(String(c)));',
  '        } else {',
  '          node.appendChild(c);',
  '        }',
  '      }',
  '    }',
  '    return node;',
  '  }',
  '',
  '  function qs(selector, root) {',
  '    return (root || document).querySelector(selector);',
  '  }',
  '',
  '  function getAgentName() {',
  '    var m = window.location.pathname.match(ROUTING_PATH_RE);',
  '    if (!m) return null;',
  '    try { return decodeURIComponent(m[1]); } catch (e) { return m[1]; }',
  '  }',
  '',
  '  // -----------------------------------------------------------------',
  '  // API accessors',
  '  // -----------------------------------------------------------------',
  '  function fetchJson(url) {',
  '    return fetch(url, { credentials: \'same-origin\' }).then(function (res) {',
  '      if (!res.ok) {',
  '        return res.text().then(function (body) {',
  '          throw new Error(\'GET \' + url + \' → \' + res.status + \' \' + (body || \'\').slice(0, 200));',
  '        });',
  '      }',
  '      return res.json();',
  '    });',
  '  }',
  '',
  '  function loadAllRoutingData(agentName) {',
  '    return Promise.all([',
  '      fetchJson(\'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/tiers\')',
  '        .catch(function (e) { return { __error: String(e && e.message || e) }; }),',
  '      fetchJson(\'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/specificity\')',
  '        .catch(function (e) { return { __error: String(e && e.message || e) }; }),',
  '      fetchJson(\'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/header-tiers\')',
  '        .catch(function (e) { return { __error: String(e && e.message || e) }; }),',
  '      fetchJson(\'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/complexity/status\')',
  '        .catch(function (e) { return { __error: String(e && e.message || e) }; }),',
  '    ]).then(function (parts) {',
'      return {',
  '        tiers: Array.isArray(parts[0]) ? parts[0] : (parts[0] && parts[0].__error ? { __error: parts[0].__error } : []),',
  '        specificity: Array.isArray(parts[1]) ? parts[1] : (parts[1] && parts[1].__error ? { __error: parts[1].__error } : []),',
  '        headerTiers: Array.isArray(parts[2]) ? parts[2] : (parts[2] && parts[2].__error ? { __error: parts[2].__error } : []),',
  '        complexity: parts[3] && !parts[3].__error ? parts[3] : (parts[3] && parts[3].__error ? { __error: parts[3].__error } : { enabled: false }),',
  '      };',
  '    });',
  '  }',
  '',
  '  // -----------------------------------------------------------------',
  '  // Why no DOM-level visibility override:',
  '  // The upstream Manifest routing page hides the Complexity +',
  '  // Task-specific surfaces via SolidJS <Show when={...}> guards.',
  '  // <Show when={false}> does not render its children AT ALL — the',
  '  // DOM has nothing to "force visible" via CSS. Trying to inject',
  '  // `display: revert !important` etc. is both futile (no DOM to target)',
  '  // AND actively harmful (it breaks the existing flex/grid layouts of',
  '  // the routing cards that ARE rendered). So the plugin takes a',
  '  // non-invasive approach: it never touches the existing DOM, never',
  '  // injects CSS, never runs a MutationObserver against the page.',
  '  //',
  '  // Instead, the plugin ONLY adds a NEW collapsible panel above the',
  '  // routing tabs. That panel fetches every routing rule via the public',
  '  // API (including the simple/standard/complex/reasoning complexity',
  '  // tiers that the upstream UI hides via the deprecation gate) and',
  '  // renders them as rows the operator can audit + delete. This way:',
  '  //',
  '  //   - The existing site is untouched (no CSS overrides, no DOM',
  '  //     mutations to existing elements, no MutationObserver).',
  '  //   - The plugin surfaces the missing tiers via a fresh UI surface,',
  '  //     not by hijacking the existing one.',
  '  //   - Toggling the plugin off via the admin UI fully removes the',
  '  //     panel on the next page refresh: the dashboard-transform bundle',
  '  //     is built per-request from enabled plugins, so a disabled plugin',
  '  //     contributes nothing to the served bundle. Refreshing the',
  '  //     routing page loads the new bundle (no show-all-router-views',
  '  //     IIFE), so the panel never renders and zero side effects remain.',
  '  // -----------------------------------------------------------------',
  '',
  '  function ensureFab() {',
  '    return ensurePanel();',
  '  }',
  '',
  '  // Backwards-compat alias — older callers reference closeModal().',
  '  // The new design is a collapsible inline panel, not a modal overlay.',
  '  function closeModal() {',
  '    if (typeof window.__showAllRouterViewsCollapse === \'function\') {',
  '      window.__showAllRouterViewsCollapse();',
  '    }',
  '  }',
  '',
  '  // Backwards-compat alias — older callers reference openModal().',
  '  // The new design is a collapsible inline panel, not a modal overlay.',
  '  function openModal() {',
  '    if (typeof window.__showAllRouterViewsExpand === \'function\') {',
  '      window.__showAllRouterViewsExpand();',
  '    } else {',
  '      // Fallback if the panel has not mounted yet (e.g. when the user',
  '      // hits this from an external call). Insert the panel inline so',
  '      // the legacy openModal() API still works.',
  '      ensurePanel();',
  '      if (typeof window.__showAllRouterViewsExpand === \'function\') {',
  '        window.__showAllRouterViewsExpand();',
  '      }',
  '    }',
  '  }',
  '',
  '  // The audit panel sits inline with the routing content — as a sibling of',
  '  // `.routing-tabs`, just before it — so the operator sees the audit surface',
  '  // without having to find a floating button or open a modal. The panel is',
  '  // collapsed by default and expands in place when the operator clicks the',
  //  "Show all routing views" header.',
  '  //',
  '  // Idempotency: a previous install left the panel in the DOM. We re-find',
  '  // it and skip the insertion; the MutationObserver and the routing-page',
  '  // detector both call this function, so we cannot naively re-append.',
  '  function ensurePanel() {',
  '    var existing = qs(\'#show-all-router-views-panel\');',
  '    if (existing) return existing;',
  '',
  '    // ── Mount point selection ───────────────────────────────────────────',
  '    // The upstream routing page has TWO layouts depending on whether',
  '    // the agent has complexity/specificity config (legacy view with',
  '    // tabs) or not (new unified view without tabs). We probe for',
  '    // both, in priority order, so the panel sits inline with the',
  '    // routing content regardless of which layout upstream shipped.',
  '    //',
  '    //   Priority 1: .routing-tabs           (legacy view — pre-tab)',
  '    //   Priority 2: .routing-cards          (clean view — pre-cards)',
  '    //   Priority 3: .routing-section       (any view — pre-section)',
  '    //   Priority 4: .container--lg          (fallback — pre-first-child)',
  '    //   Priority 5: main                    (last-resort — append)',
  '    //   Priority 6: body                    (final fallback — append)',
  '    //',
  '    // Why this priority order: priorities 1-3 land the panel in a',
  '    // sensible place inline with the routing cards. Priority 4 puts',
  '    // it at the very top of the content. Priorities 5-6 are emergency',
  '    // fallbacks that always show SOMETHING; they just put the panel',
  '    // in a less-ideal location.',
  '    var mountPoint = null;',
  '    var mountParent = null;',
  '    var mountBefore = null;',
  '    var mountStrategy = null;',
  '    var priorities = [',
  '      \'.routing-tabs\',',
  '      \'.routing-cards\',',
  '      \'.routing-section\',',
  '      \'.container--lg\',',
  '      \'main\',',
  '      \'body\',',
  '    ];',
  '    for (var pi = 0; pi < priorities.length; pi += 1) {',
  '      var candidate = qs(priorities[pi]);',
  '      if (candidate) {',
  '        mountPoint = candidate;',
  '        if (priorities[pi] === \'main\' || priorities[pi] === \'body\') {',
  '          // main/body: append (no insert-before target)',
  '          mountParent = candidate;',
  '          mountBefore = null;',
  '          mountStrategy = \'append-to-\' + priorities[pi];',
  '        } else if (priorities[pi] === \'.container--lg\') {',
  '          // container--lg: insert as the FIRST child so the panel',
  '          // sits at the top of the content (above provider icons',
  '          // row + cards + footer).',
  '          mountParent = candidate;',
  '          mountBefore = candidate.firstChild;',
  '          mountStrategy = \'prepend-to-container-lg\';',
  '        } else {',
  '          // routing-tabs / routing-cards / routing-section: insert',
  '          // before the matched element so the panel sits above it.',
  '          mountParent = candidate.parentElement;',
  '          mountBefore = candidate;',
  '          mountStrategy = \'before-\' + priorities[pi].slice(1);',
  '        }',
  '        if (mountParent) break;',
  '      }',
  '    }',
  '    if (!mountPoint || !mountParent) {',
  '      // eslint-disable-next-line no-console',
  '      console.warn(\'[show-all-router-views] no mount point found anywhere; giving up on\', window.location.pathname);',
  '      return null;',
  '    }',
  '',
  '    var panel = el(\'section\', {',
  '      id: \'show-all-router-views-panel\',',
  '      class: \'show-all-router-views__panel routing-section\',',
  '      dataset: { showAllRouterViews: \'panel\', expanded: \'false\' },',
  '      style: {',
  '        margin: \'0 0 16px 0\',',
  '        padding: \'0\',',
  '        border: \'1px solid hsl(var(--border))\',',
  '        borderRadius: \'12px\',',
  '        background: \'hsl(var(--card))\',',
  '        boxShadow: \'rgba(0,0,0,0.08) 0px 0px 0px 1px\',',
  '        overflow: \'hidden\',',
  '        fontFamily: \'var(--font-family)\',',
  '      },',
  '    });',
  '',
  '    var header = el(\'div\', {',
  '      class: \'show-all-router-views__header\',',
  '      dataset: { showAllRouterViews: \'header\' },',
  '      style: {',
  '        display: \'flex\',',
  '        alignItems: \'center\',',
  '        justifyContent: \'space-between\',',
  '        padding: \'14px 20px\',',
  '        cursor: \'pointer\',',
  '        background: \'transparent\',',
  '        userSelect: \'none\',',
  '      },',
  '    }, [',
  '      el(\'div\', { style: { display: \'flex\', alignItems: \'center\', gap: \'12px\', minWidth: 0 } }, [',
  '        el(\'h2\', {',
  '          style: {',
  '            margin: \'0\',',
  '            fontSize: \'var(--font-size-md, 15px)\',',
  '            fontWeight: \'600\',',
  '            color: \'hsl(var(--foreground))\',',
  '            whiteSpace: \'nowrap\',',
  '          },',
  '        }, [\'Reveal all routing views\']),',
  '        el(\'span\', {',
  '          id: \'show-all-router-views-summary\',',
  '          class: \'status-badge\',',
  '          style: {',
  '            display: \'inline-flex\',',
  '            alignItems: \'center\',',
  '            padding: \'2px 8px\',',
  '            borderRadius: \'9999px\',',
  '            fontSize: \'var(--font-size-xs, 12px)\',',
  '            fontWeight: \'500\',',
  '            background: \'hsl(var(--muted) / 0.6)\',',
  '            color: \'hsl(var(--muted-foreground))\',',
  '            whiteSpace: \'nowrap\',',
  '          },',
  '        }, [\'loading…\']),',
  '      ]),',
  '      el(\'button\', {',
  '        type: \'button\',',
  '        id: \'show-all-router-views-toggle\',',
  '        \'aria-label\': \'Toggle all routing views panel\',',
  '        \'aria-expanded\': \'false\',',
  '        \'aria-controls\': \'show-all-router-views-body\',',
  '        style: {',
  '          background: \'transparent\',',
  '          border: \'none\',',
  '          fontSize: \'var(--font-size-sm, 14px)\',',
  '          fontWeight: \'500\',',
  '          color: \'hsl(var(--muted-foreground))\',',
  '          cursor: \'pointer\',',
  '          padding: \'0 8px\',',
  '        },',
  '        onclick: function (e) {',
  '          e.stopPropagation();',
  '          togglePanel();',
  '        },',
  '      }, [\'Show all\']),',
  '    ]);',
  '',
  '    var body = el(\'div\', {',
  '      id: \'show-all-router-views-body\',',
  '      class: \'show-all-router-views__body\',',
  '      role: \'region\',',
  '      \'aria-label\': \'All routing views audit table\',',
  '      style: {',
  '        padding: \'0 20px 16px 20px\',',
  '        display: \'none\',',
  '        borderTop: \'1px solid hsl(var(--border))\',',
  '      },',
  '    }, [',
  '      el(\'p\', {',
  '        style: { color: \'hsl(var(--muted-foreground))\', margin: \'12px 0 0 0\' },',
  '      }, [\'Loading all routing data…\']),',
  '    ]);',
  '',
  '    // Header click expands/collapses the panel. The button inside',
  '    // the header (toggle) has its own click handler that calls',
  '    // stopPropagation, so clicking the button does not also fire',
  '    // the header click.',
  '    header.addEventListener(\'click\', function () { togglePanel(); });',
  '    header.addEventListener(\'keydown\', function (e) {',
  '      if (e.key === \'Enter\' || e.key === \' \') {',
  '        e.preventDefault();',
  '        togglePanel();',
  '      }',
  '    });',
  '    header.setAttribute(\'tabindex\', \'0\');',
  '    header.setAttribute(\'role\', \'button\');',
  '',
  '    panel.appendChild(header);',
  '    panel.appendChild(body);',
  '    // Insert as a sibling of `.routing-tabs`, just before it. The',
  '    // panel therefore appears above the routing tabs in the page',
  '    // flow — exactly where the operator would expect an audit',
  '    // surface to live.',
    '    if (mountBefore) {',
    '      mountParent.insertBefore(panel, mountBefore);',
    '    } else {',
    '      mountParent.appendChild(panel);',
    '    }',
    '    // eslint-disable-next-line no-console',
    "    console.log('[show-all-router-views] panel mounted (' + mountStrategy + ') on', window.location.pathname);",
  '',
  '    // Wire the legacy back-compat shims BEFORE we trigger the first',
  '    // fetch, so an openModal() call from any path is a no-op until',
  '    // the panel is mounted and ready.',
  '    window.__showAllRouterViewsExpand = expandPanel;',
  '    window.__showAllRouterViewsCollapse = collapsePanel;',
  '',
  '    // Trigger the first fetch so the summary badge updates from',
  //  "loading…" to the real count. We do not auto-expand the panel —',
  '    //  collapsed by default is the operator-friendly state. The',
  '    //  expand toggle below uses the same data when the operator',
  //  clicks the header.',
  '    var agentName = getAgentName();',
  '    if (agentName) {',
  '      loadAllRoutingData(agentName).then(function (data) {',
  '        var counts = summarizeData(data);',
  '        var summary = qs(\'#show-all-router-views-summary\', panel);',
  '        if (summary) {',
  '          summary.textContent = formatSummary(counts);',
  '        }',
  '        // Cache the data for when the operator clicks "Show all".',
  '        cachedData = data;',
  '        cachedAgentName = agentName;',
  '      }).catch(function () {',
  '        var summary = qs(\'#show-all-router-views-summary\', panel);',
  '        if (summary) {',
  '          summary.textContent = \'failed to load\';',
  '        }',
  '      });',
  '    }',
  '',
  '    return panel;',
  '  }',
  '',
  '  // Cached data + agent name for the expand path. Reset on each fetch',
  '  //  (the install function re-fetches on every panel mount).',
  '  var cachedData = null;',
  '  var cachedAgentName = null;',
  '',
  '  function formatSummary(counts) {',
  '    var total = counts.tiers + counts.specificity + counts.headerTiers;',
  '    if (total === 0) return \'0 configured rules\';',
  '    var parts = [];',
  '    if (counts.tiers > 0) parts.push(counts.tiers + \' tier override\' + (counts.tiers === 1 ? \'\' : \'s\'));',
  '    if (counts.specificity > 0) parts.push(counts.specificity + \' specificity\');',
  '    if (counts.headerTiers > 0) parts.push(counts.headerTiers + \' header tier\' + (counts.headerTiers === 1 ? \'\' : \'s\'));',
  '    return total + \' rules: \' + parts.join(\', \');',
  '  }',
  '',
  '  function summarizeData(data) {',
  '    return {',
  '      tiers: (data.tiers || []).length,',
  '      specificity: (data.specificity || []).length,',
  '      headerTiers: (data.headerTiers || []).length,',
  '    };',
  '  }',
  '',
  '  function togglePanel() {',
  '    var panel = qs(\'#show-all-router-views-panel\');',
  '    if (!panel) return;',
  '    var isExpanded = panel.getAttribute(\'data-expanded\') === \'true\';',
  '    if (isExpanded) {',
  '      collapsePanel();',
  '    } else {',
  '      expandPanel();',
  '    }',
  '  }',
  '',
  '  function expandPanel() {',
  '    var panel = qs(\'#show-all-router-views-panel\');',
  '    if (!panel) return;',
  '    var body = qs(\'#show-all-router-views-body\', panel);',
  '    if (!body) return;',
  '    panel.setAttribute(\'data-expanded\', \'true\');',
  '    body.style.display = \'block\';',
  '    var toggle = qs(\'#show-all-router-views-toggle\', panel);',
  '    if (toggle) {',
  '      toggle.setAttribute(\'aria-expanded\', \'true\');',
  '      toggle.textContent = \'Hide\';',
  '    }',
  '    // Render the full audit table. Use the cached data when available;',
  '    // otherwise re-fetch.',
  '    var agentName = getAgentName();',
  '    if (!agentName) return;',
  '    if (cachedData && cachedAgentName === agentName) {',
  '      renderAuditBody(body, agentName, cachedData);',
  '    } else {',
  '      body.innerHTML = \'\';',
  '      body.appendChild(el(\'p\', {',
  '        style: { color: \'hsl(var(--muted-foreground))\', margin: \'12px 0 0 0\' },',
  '      }, [\'Loading all routing data…\']));',
  '      loadAllRoutingData(agentName).then(function (data) {',
  '        cachedData = data;',
  '        cachedAgentName = agentName;',
  '        renderAuditBody(body, agentName, data);',
  '      }).catch(function (e) {',
  '        body.innerHTML = \'\';',
  '        body.appendChild(el(\'p\', {',
  '          style: { color: \'hsl(var(--destructive))\' },',
  '        }, [\'Failed to load routing data: \' + (e && e.message || e)]));',
  '      });',
  '    }',
  '  }',
  '',
  '  function collapsePanel() {',
  '    var panel = qs(\'#show-all-router-views-panel\');',
  '    if (!panel) return;',
  '    var body = qs(\'#show-all-router-views-body\', panel);',
  '    if (!body) return;',
  '    panel.setAttribute(\'data-expanded\', \'false\');',
  '    body.style.display = \'none\';',
  '    var toggle = qs(\'#show-all-router-views-toggle\', panel);',
  '    if (toggle) {',
  '      toggle.setAttribute(\'aria-expanded\', \'false\');',
  '      toggle.textContent = \'Show all\';',
  '    }',
  '  }',
  '',
  '  function routeLabel(route) {',
  '    if (!route) return \'— (auto) —\';',
  '    var provider = route.provider || \'?\';',
  '    var authType = route.authType ? \' / \' + route.authType : \'\';',
  '    var model = route.model || \'?\';',
  '    return provider + authType + \' :: \' + model;',
  '  }',
  '',
  '  function tierLabel(tier) {',
  '    if (!tier) return \'—\';',
  '    return tier + (tier === \'default\' ? \' (fallback for everything else)\' : \'\');',
  '  }',
  '',
  '  function formatBool(b) { return b ? \'true\' : \'false\'; }',
  '',
  '  // Pure read-only table renderer. No delete buttons, no action',
  '  // column. The official upstream API for editing routing lives in',
  '  // the dashboard UI (RoutingTabs, RoutingDefaultTierSection,',
  '  // RoutingSpecificitySection, RoutingHeaderTiersSection); this',
  '  // plugin only surfaces what the deprecation gate hides.',
  '  function renderSection(title, rows, columns) {',
  '    var section = el(\'section\', {',
  '      style: { marginBottom: \'24px\' },',
  '      dataset: { showAllRouterViews: \'section\' },',
  '    });',
  '    section.appendChild(el(\'h3\', {',
  '      style: {',
  '        margin: \'0 0 8px 0\',',
  '        fontSize: \'var(--font-size-md, 15px)\',',
  '        fontWeight: \'600\',',
  '        color: \'hsl(var(--foreground))\',',
  '      },',
  '    }, [title + \' (\' + rows.length + \')\']));',
  '    if (rows.length === 0) {',
  '      section.appendChild(el(\'p\', {',
  '        style: {',
  '          color: \'hsl(var(--muted-foreground))\',',
  '        },',
  '      }, [\'(no rows)\']));',
  '      return section;',
  '    }',
  '    var table = el(\'table\', {',
  '      style: {',
  '        width: \'100%\',',
  '        borderCollapse: \'collapse\',',
  '        fontSize: \'var(--font-size-xs, 12px)\',',
  '        color: \'hsl(var(--foreground))\',',
  '      },',
  '    });',
  '    var thead = el(\'thead\', null, [',
  '      el(\'tr\', null, columns.map(function (c) {',
  '        return el(\'th\', {',
  '          style: {',
  '            textAlign: \'left\',',
  '            padding: \'6px 8px\',',
  '            borderBottom: \'1px solid hsl(var(--border))\',',
  '            fontWeight: \'600\',',
  '            whiteSpace: \'nowrap\',',
  '          },',
  '        }, [c.label]);',
  '      })),',
  '    ]);',
  '    table.appendChild(thead);',
  '    var tbody = el(\'tbody\');',
  '    rows.forEach(function (row) {',
  '      var tr = el(\'tr\', { dataset: { showAllRouterViews: \'row\', rowId: row.id || row.category || row.tier || \'\' } });',
  '      columns.forEach(function (c) {',
  '        tr.appendChild(el(\'td\', {',
  '          style: {',
  '            padding: \'6px 8px\',',
  '            borderBottom: \'1px solid hsl(var(--border))\',',
  '            verticalAlign: \'top\',',
  '            whiteSpace: \'nowrap\',',
  '          },',
  '        }, [c.render ? c.render(row) : (row[c.key] === null || row[c.key] === undefined ? \'—\' : String(row[c.key]))]));',
  '      });',
  '      tbody.appendChild(tr);',
  '    });',
  '    table.appendChild(tbody);',
  '    section.appendChild(table);',
  '    return section;',
  '  }',
  '',
  '  function renderAuditBody(body, agentName, data) {',
  '    body.innerHTML = \'\';',
  '',
  '    body.appendChild(el(\'p\', {',
  '      style: {',
  '        margin: \'0 0 16px 0\',',
  '        fontSize: \'var(--font-size-xs, 12px)\',',
  '        color: \'hsl(var(--muted-foreground))\',',
  '      },',
'    }, [',
      '      \'Read-only audit. Showing every row from the public Manifest routing API for this agent. \',',
      '      \'Note: the message-row tier field reads standard for ANY specificity- or header-tier-matched request (per \',',
      '      \'packages/backend/src/routing/resolve/resolve.service.ts, both resolveSpecificity and \',',
      '      \'resolveHeaderTier hardcode tier: standard in the response). If you see tier: standard \',',
      '      \'in routing metadata, the model is the one configured for that category or header tier -- \',',
      '      \'not the standard complexity tier. Stale rows (e.g. override_route pointing to a model the \',',
      '      \'agent no longer has) appear here even when the upstream UI hides them. \',',
    '  ]));',
  '',
'    // Tiers (complexity + default)',
  '    var tierRows = [];',
  '    if (data.tiers && data.tiers.__error) {',
  '      body.appendChild(el(\'p\', { style: { color: \'hsl(var(--destructive))\' } },',
  '        [\'Tiers API error: \' + data.tiers.__error]));',
  '    } else {',
  '      // When complexity routing is disabled, the backend\'s resolve.service.ts',
  '      // short-circuits every request to the `default` tier. The simple/',
  '      // standard/complex/reasoning rows are auto-created on agent bootstrap',
  '      // (upstream hard-codes TIER_SLOTS = {simple, standard, complex,',
  '      // reasoning, default}) but the routing engine never reads them.',
  '      // Showing them as "configurable rows" is misleading — the operator',
  '      // cannot delete them via the public API (only clearOverride exists,',
  '      // and it has a separate upstream bug that throws 400 on stream-mode',
  '      // tiers without stream-capable fallbacks). Hide the inert rows and',
  '      // show only the `default` row + a notice explaining the state.',
  '      var complexityEnabled = !!(data.complexity && !data.complexity.__error && data.complexity.enabled);',
  '      var allTierRows = (data.tiers || []).map(function (t) {',
  '        return {',
  '          id: t.id,',
  '          tier: t.tier,',
  '          override_model: t.override_model || (t.override_route && t.override_route.model) || null,',
  '          auto_assigned_model: t.auto_assigned_model || (t.auto_assigned_route && t.auto_assigned_route.model) || null,',
  '          override_route: t.override_route || null,',
  '          response_mode: t.response_mode || null,',
  '          fallback_routes: t.fallback_routes || null,',
  '        };',
  '      });',
  '      if (complexityEnabled) {',
  '        tierRows = allTierRows;',
  '      } else {',
  '        // Show ALL 5 tier rows. Even when complexity is disabled, the',
  '        // operator wants to SEE the auto-created rows (auto-assigned',
  '        // models, no override) so they can verify nothing is hiding.',
  '        // The complexity status footer below explains the routing',
  '        // semantics, and the toggle button is the official way to',
  '        // make the rows inert. We do NOT filter rows here — that',
  '        // would hide the very data the operator came to see.',
  '        tierRows = allTierRows;',
  '      }',
  '      body.appendChild(renderSection(',
  '        \'Complexity tiers (tier_assignments)\',',
  '        tierRows,',
  '        [',
  '          { label: \'Tier\', key: \'tier\', render: function (r) { return tierLabel(r.tier); } },',
  '          { label: \'Override model\', render: function (r) { return routeLabel(r.override_route) || (r.override_model || \'—\'); } },',
  '          { label: \'Auto-assigned\', render: function (r) { return r.auto_assigned_model || \'—\'; } },',
  '          { label: \'Response mode\', key: \'response_mode\' },',
  '          { label: \'Fallbacks\', render: function (r) {',
  '            return (r.fallback_routes || []).map(routeLabel).join(\' → \') || \'—\';',
  '          } },',
  '        ],',
  '      ));',
  '    }',
  '',
  '    // Specificity (task-specific)',
  '    if (data.specificity && data.specificity.__error) {',
  '      body.appendChild(el(\'p\', { style: { color: \'hsl(var(--destructive))\' } },',
  '        [\'Specificity API error: \' + data.specificity.__error]));',
  '    } else {',
  '      var specificityRows = (data.specificity || []).map(function (a) {',
  '        return {',
  '          id: a.id,',
  '          category: a.category,',
  '          is_active: a.is_active,',
  '          override_model: a.override_model || (a.override_route && a.override_route.model) || null,',
  '          override_route: a.override_route || null,',
  '          response_mode: a.response_mode || null,',
  '          fallback_routes: a.fallback_routes || null,',
  '        };',
  '      });',
  '      body.appendChild(renderSection(',
  '        \'Task-specific routing (specificity_assignments)\',',
  '        specificityRows,',
  '        [',
  '          { label: \'Category\', key: \'category\' },',
  '          { label: \'Active\', render: function (r) { return formatBool(r.is_active); } },',
  '          { label: \'Override model\', render: function (r) { return routeLabel(r.override_route) || (r.override_model || \'—\'); } },',
  '          { label: \'Response mode\', key: \'response_mode\' },',
  '          { label: \'Fallbacks\', render: function (r) {',
  '            return (r.fallback_routes || []).map(routeLabel).join(\' → \') || \'—\';',
  '          } },',
  '        ],',
  '      ));',
  '    }',
  '',
  '    // Header tiers (custom routing)',
  '    if (data.headerTiers && data.headerTiers.__error) {',
  '      body.appendChild(el(\'p\', { style: { color: \'hsl(var(--destructive))\' } },',
  '        [\'Header tiers API error: \' + data.headerTiers.__error]));',
  '    } else {',
  '      var headerTierRows = (data.headerTiers || []).map(function (t) {',
  '        return {',
  '          id: t.id,',
  '          name: t.name,',
  '          header_key: t.header_key,',
  '          header_value: t.header_value,',
  '          enabled: t.enabled,',
  '          sort_order: t.sort_order,',
  '          override_model: t.override_model || (t.override_route && t.override_route.model) || null,',
  '          override_route: t.override_route || null,',
  '          fallback_routes: t.fallback_routes || null,',
  '          response_mode: t.response_mode || null,',
  '        };',
  '      });',
  '      body.appendChild(renderSection(',
  '        \'Custom header-triggered routing (header_tiers)\',',
  '        headerTierRows,',
  '        [',
  '          { label: \'Name\', key: \'name\' },',
  '          { label: \'Header\', render: function (r) { return (r.header_key || \'\') + \': \' + (r.header_value || \'\'); } },',
  '          { label: \'Enabled\', render: function (r) { return formatBool(r.enabled); } },',
  '          { label: \'Sort\', key: \'sort_order\' },',
  '          { label: \'Override model\', render: function (r) { return routeLabel(r.override_route) || (r.override_model || \'—\'); } },',
  '          { label: \'Fallbacks\', render: function (r) {',
  '            return (r.fallback_routes || []).map(routeLabel).join(\' → \') || \'—\';',
  '          } },',
  '        ],',
  '      ));',
  '    }',
  '',
  '    // Complexity status + toggle.',
  '    //',
  '    // This is the OFFICIAL, upstream-blessed fix for the operator\'s',
  '    // "calls accidentally route to simple" problem. Per the upstream',
  '    // `resolve.service.ts::resolveRouting()` logic, when',
  '    // complexity_routing_enabled = false, the engine short-circuits',
  '    // every request to the `default` tier — the 4 complexity-tier rows',
  '    // become inert and requests stop landing on simple/standard/etc.',
  '    //',
  '    // The toggle endpoint is `POST /api/v1/routing/<agent>/complexity/toggle`',
  '    // (per `packages/backend/src/routing/tier.controller.ts`). There is',
  '    // NO upstream endpoint to delete the auto-created tier rows',
  '    // themselves — the only operator-controllable lever is this toggle.',
  '    // This is the cleanest, most official, least hacky way to fix the',
  '    // operator\'s problem.',
  '    if (data.complexity && data.complexity.__error) {',
  '      body.appendChild(el(\'p\', { style: { color: \'hsl(var(--destructive))\' } },',
  '        [\'Complexity status API error: \' + data.complexity.__error]));',
  '    } else {',
  '      var complexitySection = el(\'section\', { style: { marginTop: \'8px\' } }, [',
  '        el(\'h3\', {',
  '          style: {',
  '            margin: \'0 0 8px 0\',',
  '            fontSize: \'var(--font-size-md, 15px)\',',
  '            fontWeight: \'600\',',
  '            color: \'hsl(var(--foreground))\',',
  '          },',
  '        }, [\'Complexity routing status\']),',
  '        el(\'p\', {',
  '          style: { margin: \'0 0 12px 0\', fontSize: \'var(--font-size-sm, 14px)\', color: \'hsl(var(--muted-foreground))\', lineHeight: \'1.5\' },',
  '        }, [',
  '          complexityEnabled',
  '            ? \'Enabled. Every request is classified into one of the 4 tiers above (simple/standard/complex/reasoning) and routed to that row. To stop this, click Disable below.\'',
  '            : \'Disabled. The engine short-circuits every request to the `default` tier — the 4 complexity-tier rows above (simple/standard/complex/reasoning) are auto-created by the backend on agent bootstrap and remain in the DB but are not used for routing.\',',
  '        ]),',
  '      ]);',
  '      var complexityToggle = el(\'button\', {',
  '        type: \'button\',',
  '        dataset: { showAllRouterViews: \'complexity-toggle\' },',
  '        style: {',
  '          padding: \'8px 14px\',',
  '          borderRadius: \'6px\',',
  '          border: \'1px solid hsl(var(--border))\',',
  '          background: complexityEnabled ? \'hsl(var(--muted) / 0.5)\' : \'hsl(var(--foreground))\',',
  '          color: complexityEnabled ? \'hsl(var(--foreground))\' : \'hsl(var(--background))\',',
  '          cursor: \'pointer\',',
  '          fontFamily: \'var(--font-family)\',',
  '          fontSize: \'var(--font-size-sm, 13px)\',',
  '          fontWeight: \'500\',',
  '        },',
  '        onclick: function () {',
  '          var btn = complexityToggle;',
  '          var prevText = btn.textContent;',
  '          btn.disabled = true;',
  '          btn.textContent = \'Working…\';',
  '          fetch(\'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/complexity/toggle\', {',
  '            method: \'POST\',',
  '            credentials: \'same-origin\',',
  '            headers: { \'Content-Type\': \'application/json\' },',
  '            body: JSON.stringify({}),',
  '          }).then(function (res) {',
  '            if (!res.ok) {',
  '              return res.text().then(function (t) {',
  '                throw new Error(\'Toggle failed: HTTP \' + res.status + \' — \' + t.slice(0, 200));',
  '              });',
  '            }',
  '            return res.json().catch(function () { return {}; });',
  '          }).then(function () {',
  '            // Re-fetch the audit data so the table + status footer',
  '            // reflect the new state.',
  '            return loadAllRoutingData(agentName).then(function (fresh) {',
  '              cachedData = fresh;',
  '              cachedAgentName = agentName;',
  '              renderAuditBody(body, agentName, fresh);',
  '            });',
  '          }).catch(function (err) {',
  '            window.alert(\'Toggle complexity failed: \' + (err && err.message || err));',
  '            btn.disabled = false;',
  '            btn.textContent = prevText;',
  '          });',
  '        },',
  '      }, [complexityEnabled ? \'Disable complexity routing\' : \'Enable complexity routing\']);',
  '      complexitySection.appendChild(complexityToggle);',
  '      body.appendChild(complexitySection);',
  '    }',
  '  }',
  '',
  '  function onRoutePage() {',
  '    return getAgentName() !== null;',
  '  }',
  '',
  '  function installOnCurrentRoute() {',
  '    if (!onRoutePage()) return;',
  '    ensureFab();',
  '  }',
  '',
  '  if (document.readyState === \'loading\') {',
  '    document.addEventListener(\'DOMContentLoaded\', installOnCurrentRoute, { once: true });',
  '  } else {',
  '    installOnCurrentRoute();',
  '  }',
  '',
  '  var lastPath = window.location.pathname;',
  '  var observer = new MutationObserver(function () {',
  '    var currentPath = window.location.pathname;',
  '    if (currentPath !== lastPath) {',
  '      lastPath = currentPath;',
  '      if (!onRoutePage()) {',
  '        // Leaving the routing page: tear the panel down so it',
  '        // does not linger on Overview / Messages / Settings / etc.',
  '        var panel = qs(\'#show-all-router-views-panel\');',
  '        if (panel && panel.parentNode) panel.parentNode.removeChild(panel);',
  '        closeModal();',
  '      } else {',
  '        // Re-entering the routing page after a navigation:',
  '        // re-mount the panel. ensureFab() is idempotent — it',
  '        // checks for the existing DOM before inserting.',
  '        ensureFab();',
  '      }',
  '    }',
  '  });',
  '  observer.observe(document.body, { childList: true, subtree: true });',
  '',
  '  window.addEventListener(\'popstate\', installOnCurrentRoute);',
  '',
  '  window.__manifestPluginsDashboardTransform.push({',
  '    id: PLUGIN_ID,',
  '    version: SCRIPT_VERSION,',
  '    install: installOnCurrentRoute,',
  '  });',
  '})();',
].join('\n');

export class ShowAllRouterViewsPlugin implements DashboardTransformPlugin {
  static readonly metadata: PluginMetadata = SHOW_ALL_ROUTER_VIEWS_PLUGIN_METADATA;

  getDashboardScript(): string {
    return SHOW_ALL_ROUTER_VIEWS_SCRIPT;
  }
}
