/**
 * ShowAllRouterViewsPlugin — dashboard-transform plugin that un-hides every
 * router view on the Manifest routing page so operators can audit stale
 * routing rules and clean them up.
 *
 * Background: as of commit `49ef687` (Manifest 6.x), the upstream routing
 * page (`packages/frontend/src/pages/Routing.tsx`) applies a
 * "deprecation gate" that hides both the **Complexity** and the
 * **Task-specific** routing surfaces from agents that have never
 * configured them. The gate is sticky per session (`legacyComplexityVisible`
 * and `legacySpecificityVisible` createSignals), and the `Custom` (header
 * tier) surface is gated separately by a per-tier `enabled` flag.
 *
 * Concretely, the upstream gate means a clean agent only sees the
 * `Default` and `Custom` tabs; the `Complexity` and `Task-specific`
 * sections never render — even if database rows exist for them (e.g.
 * from a previous agent that was migrated, a deleted header_tier, an
 * override_route that points to a model the agent no longer has
 * credentials for, or a hand-inserted DB row).
 *
 * This plugin's goal: give the operator one click to surface ALL router
 * views, including ones the upstream UI has hidden. The plugin emits a
 * single browser-side script that:
 *   1. Detects the routing page (URL pattern `/agents/<name>/routing`).
 *   2. Removes the deprecation gate by overriding the upstream
 *      `legacyComplexityVisible` and `legacySpecificityVisible` signals
 *      (SolidJS exposes these as `getter`/`setter` closures on the
 *      component's owner; we walk the DOM for the routing root and flip
 *      both signals to `true`, then force a re-render by toggling the
 *      active tab).
 *   3. Shows a "Reveal all routing views" floating action button (FAB)
 *      in the bottom-right corner of the routing page. The FAB opens a
 *      modal that fetches every routing surface via the public API and
 *      renders a flat table — including rows the upstream UI would have
 *      hidden because they are `is_active = false`, `override_route = null`,
 *      etc. This is the operator's audit surface.
 *   4. The audit modal also surfaces a one-click "Delete" affordance
 *      per row that calls the existing DELETE endpoint (e.g.
 *      `DELETE /api/v1/routing/<agent>/header-tiers/<id>`,
 *      `DELETE /api/v1/routing/<agent>/tiers/<tier>`,
 *      `DELETE /api/v1/routing/<agent>/specificity/<category>`) so
 *      operators can remove the stale rule without leaving the
 *      dashboard.
 *
 * The plugin is intentionally read-by-default and write-on-click: it
 * does not mutate any routing config until the operator explicitly
 * clicks the delete button on a specific row.
 *
 * Idempotency:
 *   - `getDashboardScript()` is pure: same input → same string. Safe
 *     to call repeatedly.
 *   - The injected script uses `data-show-all-router-views` markers
 *     on every DOM element it creates so re-running the script is a
 *     no-op.
 *   - The MutationObserver reconnects automatically when the
 *     dashboard unmounts and remounts (SolidJS route change). It
 *     also debounces its own work so a 100ms barrage of DOM events
 *     doesn't run the patch logic 100 times.
 *
 * Behavior on non-routing pages:
 *   - The script is a no-op. It only activates on the routing page.
 *   - The FAB is rendered only on the routing page; on other pages
 *     nothing is added to the DOM.
 *
 * Plugin kind: `dashboard-transform`. This is a new kind introduced
 * by this plugin; the host walks the registry, collects
 * `getDashboardScript()` output from every enabled `dashboard-transform`
 * plugin, and the dashboard mount overlay injects a single combined
 * `<script>` tag that loads them. See `src/index.ts` for the kind
 * enum and the admin server's `/admin/dashboard-transform/all.js`
 * route.
 *
 * Limitations:
 *   - The SolidJS signal walk assumes the upstream shape: the
 *     routing page is the third-level child of `<main>` (under
 *     `.container--lg`), and the SolidJS owner is attached via the
 *     standard `_$$_Owner` property on the rendered DOM element.
 *     If upstream restructures, the script's signal-walk falls back
 *     to a DOM-level approach (showing the FAB regardless).
 *   - The "delete" affordance calls the public API endpoints. If an
 *     endpoint is removed or renamed upstream, the script surfaces
 *     the error in a toast and the operator can use `npm run
 *     plugins:disable -- show-all-router-views` to fall back to
 *     the upstream UI.
 */
import type {
  DashboardTransformPlugin,
  PluginKind,
  PluginMetadata,
} from '../..';

export const SHOW_ALL_ROUTER_VIEWS_PLUGIN_KIND: PluginKind = 'dashboard-transform';

export const SHOW_ALL_ROUTER_VIEWS_PLUGIN_METADATA: PluginMetadata = Object.freeze({
  id: 'show-all-router-views',
  name: 'Show all router views',
  version: '0.1.0',
  description:
    'Un-hides the Complexity and Task-specific routing tabs on the ' +
    'Manifest routing page and adds a "Reveal all routing views" panel ' +
    'that lists every configured routing rule (including stale ones the ' +
    'upstream UI hides via the deprecation gate). Use it to audit and ' +
    'clean up header tiers, specificity assignments, and complexity ' +
    'tier overrides that are still routing but no longer visible in ' +
    'the dashboard.',
  kind: SHOW_ALL_ROUTER_VIEWS_PLUGIN_KIND,
});

/**
 * The browser-side script that the admin server concatenates into
 * `/admin/dashboard-transform/all.js` for every enabled
 * `dashboard-transform` plugin.
 *
 * Shape: an IIFE that registers one entry on `window.__manifestPluginsDashboardTransform`.
 * The single combined bundle iterates that registry on `DOMContentLoaded`
 * and runs each entry. This shape lets the host's load order stay
 * stable regardless of how many `dashboard-transform` plugins are
 * installed, and lets each plugin's script fail independently (one
 * broken plugin does not abort the others).
 *
 * Source of truth: this constant. Authoring the JS inline (rather
 * than shipping a separate `.js` file and bundling it with esbuild)
 * keeps the plugin's runtime shape inside the TypeScript type system
 * so plugin authors get autocomplete and the build catches syntax
 * errors at compile time.
 *
 * Minification: the admin server does NOT minify the bundle. The
 * total payload across all plugins is well under the 16KB gzip
 * threshold for above-the-fold scripts, and unminified output makes
 * it trivial to debug from the browser devtools ("which plugin
 * emitted this line?").
 */
export const SHOW_ALL_ROUTER_VIEWS_SCRIPT: string = [
  '(function () {',
  '  \'use strict\';',
  '  if (typeof window === \'undefined\') return;',
  '',
  '  if (window.__manifestPluginsDashboardTransform === undefined) {',
  '    window.__manifestPluginsDashboardTransform = [];',
  '  }',
  '  if (window.__manifestPluginsDashboardTransform.some(function (e) { return e.id === \'show-all-router-views\'; })) {',
  '    return;',
  '  }',
  '',
  '  var PLUGIN_ID = \'show-all-router-views\';',
  '  var SCRIPT_VERSION = \'0.1.0\';',
  '',
  '  // The routing page URL pattern. Captures the agent name (URL-decoded by the server before any fetch).',
  '  var ROUTING_PATH_RE = /^\\/agents\\/([^/]+)\\/routing\\/?$/;',
  '',
  '  function el(tag, attrs, children) {',
  '    var node = document.createElement(tag);',
  '    if (attrs) {',
  '      for (var k in attrs) {',
  '        if (Object.prototype.hasOwnProperty.call(attrs, k)) {',
  '          var v = attrs[k];',
  '          if (v === null || v === undefined || v === false) continue;',
  '          if (k === \'class\') node.className = v;',
  '          else if (k === \'style\' && typeof v === \'object\') {',
  '            for (var sk in v) {',
  '              if (Object.prototype.hasOwnProperty.call(v, sk)) {',
  '                node.style[sk] = v[sk];',
  '              }',
  '            }',
  '          } else if (k.indexOf(\'on\') === 0 && typeof v === \'function\') {',
  '            node.addEventListener(k.slice(2).toLowerCase(), v);',
  '          } else if (k === \'dataset\' && typeof v === \'object\') {',
  '            for (var dk in v) {',
  '              if (Object.prototype.hasOwnProperty.call(v, dk)) {',
  '                node.dataset[dk] = v[dk];',
  '              }',
  '            }',
  '          } else {',
  '            node.setAttribute(k, v === true ? \'\' : String(v));',
  '          }',
  '        }',
  '      }',
  '    }',
  '    if (children !== undefined && children !== null) {',
  '      if (!Array.isArray(children)) children = [children];',
  '      for (var i = 0; i < children.length; i += 1) {',
  '        var c = children[i];',
  '        if (c === null || c === undefined || c === false) continue;',
  '        if (typeof c === \'string\' || typeof c === \'number\') {',
  '          node.appendChild(document.createTextNode(String(c)));',
  '        } else {',
  '          node.appendChild(c);',
  '        }',
  '      }',
  '    }',
  '    return node;',
  '  }',
  '',
  '  function qs(selector, root) {',
  '    return (root || document).querySelector(selector);',
  '  }',
  '',
  '  function getAgentName() {',
  '    var m = window.location.pathname.match(ROUTING_PATH_RE);',
  '    if (!m) return null;',
  '    try { return decodeURIComponent(m[1]); } catch (e) { return m[1]; }',
  '  }',
  '',
  '  // -----------------------------------------------------------------',
  '  // API accessors',
  '  // -----------------------------------------------------------------',
  '  function fetchJson(url) {',
  '    return fetch(url, { credentials: \'same-origin\' }).then(function (res) {',
  '      if (!res.ok) {',
  '        return res.text().then(function (body) {',
  '          throw new Error(\'GET \' + url + \' → \' + res.status + \' \' + (body || \'\').slice(0, 200));',
  '        });',
  '      }',
  '      return res.json();',
  '    });',
  '  }',
  '',
  '  function deleteJson(url) {',
  '    return fetch(url, { method: \'DELETE\', credentials: \'same-origin\' }).then(function (res) {',
  '      if (!res.ok) {',
  '        return res.text().then(function (body) {',
  '          throw new Error(\'DELETE \' + url + \' → \' + res.status + \' \' + (body || \'\').slice(0, 200));',
  '        });',
  '      }',
  '      return res.json().catch(function () { return {}; });',
  '    });',
  '  }',
  '',
  '  function loadAllRoutingData(agentName) {',
  '    return Promise.all([',
  '      fetchJson(\'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/tiers\')',
  '        .catch(function (e) { return { __error: String(e && e.message || e) }; }),',
  '      fetchJson(\'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/specificity-assignments\')',
  '        .catch(function (e) { return { __error: String(e && e.message || e) }; }),',
  '      fetchJson(\'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/header-tiers\')',
  '        .catch(function (e) { return { __error: String(e && e.message || e) }; }),',
  '      fetchJson(\'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/complexity-status\')',
  '        .catch(function (e) { return { __error: String(e && e.message || e) }; }),',
  '    ]).then(function (parts) {',
  '      return {',
  '        tiers: Array.isArray(parts[0]) ? parts[0] : (parts[0] && parts[0].__error ? { __error: parts[0].__error } : []),',
  '        specificity: Array.isArray(parts[1]) ? parts[1] : (parts[1] && parts[1].__error ? { __error: parts[1].__error } : []),',
  '        headerTiers: Array.isArray(parts[2]) ? parts[2] : (parts[2] && parts[2].__error ? { __error: parts[2].__error } : []),',
  '        complexity: parts[3] && !parts[3].__error ? parts[3] : (parts[3] && parts[3].__error ? { __error: parts[3].__error } : { enabled: false }),',
  '      };',
  '    });',
  '  }',
  '',
  '  // -----------------------------------------------------------------',
  '  // Visibility override: force-show anything upstream hid at the DOM level.',
  '  // Upstream Manifest can hide a router view several ways:',
  '  //  1. SolidJS <Show when={false}> — children never mount.',
  '  //  2. display: none on a parent or the element itself.',
  '  //  3. visibility: hidden — element is laid out but invisible.',
  '  //  4. opacity: 0 — element is visible to layout and a11y but transparent.',
  '  //  5. hidden HTML attribute — equivalent to display: none.',
  '  //  6. aria-hidden="true" — a11y-hidden, often paired with display: none.',
  '  //  7. Negative tabindex, pointer-events: none + low opacity — deactivated tabs.',
  '  //  8. Class-based hiding — class="hidden", class="d-none", inline display: none.',
  '  //  9. Conditional rendering by class on a parent — ancestor gets is-collapsed.',
  '  //  10. z-index: -1 + position: absolute off-screen — rare but seen in slide-out panels.',
  '  // Strategy: defense-in-depth override: install a <style> element that',
  '  // forces every router-tab and routing-card descendant to render with',
  '  // display and visibility defaults, AND walk the DOM to clean up',
  '  // inline styles + the hidden attr + aria-hidden on each element that',
  '  // could plausibly be a router surface. The MutationObserver re-applies',
  '  // this on every relevant DOM mutation so re-renders do not re-hide.',
  '  // -----------------------------------------------------------------',
  '',
  '  function isElementHidden(node) {',
  '    if (!node || node.nodeType !== 1) return false;',
  '    if (node.hasAttribute && node.hasAttribute(\'hidden\')) return true;',
  '    var style = window.getComputedStyle(node);',
  '    if (!style) return false;',
  '    if (style.display === \'none\') return true;',
  '    if (style.visibility === \'hidden\' || style.visibility === \'collapse\') return true;',
  '    if (parseFloat(style.opacity || \'1\') === 0) return true;',
  '    return false;',
  '  }',
  '',
  '  function forceVisible(node) {',
  '    if (!node || node.nodeType !== 1) return;',
  '    if (node.hasAttribute && node.hasAttribute(\'hidden\')) node.removeAttribute(\'hidden\');',
  '    if (node.getAttribute && node.getAttribute(\'aria-hidden\') === \'true\') node.removeAttribute(\'aria-hidden\');',
  '    if (node.getAttribute && node.getAttribute(\'data-show-all-router-views-forced\') === \'1\') return;',
  '    var inline = node.style || {};',
  '    var hadBlocking = false;',
  '    if (inline.display === \'none\') { inline.display = \'\'; hadBlocking = true; }',
  '    if (inline.visibility === \'hidden\' || inline.visibility === \'collapse\') { inline.visibility = \'\'; hadBlocking = true; }',
  '    if (inline.opacity === \'0\') { inline.opacity = \'\'; hadBlocking = true; }',
  '    if (hadBlocking) {',
  '      node.setAttribute(\'data-show-all-router-views-forced\', \'1\');',
  '    }',
  '  }',
  '',
  '  function isRouterSurface(node) {',
  '    if (!node || node.nodeType !== 1) return false;',
  '    var cls = (node.className && typeof node.className === \'string\') ? node.className : \'\';',
  '    if (!cls) return false;',
  '    return /(^|\\s)(routing-tab|panel__tab|routing-card|routing-section|routing-tabs|routing-cards|tab--hidden|tab--disabled|tab--collapsed)/.test(cls);',
  '  }',
  '',
  '  function applyVisibilityOverride(root) {',
  '    if (!root) return;',
  '    var styleEl = document.getElementById(\'show-all-router-views-style\');',
  '    if (!styleEl) {',
  '      styleEl = el(\'style\', { id: \'show-all-router-views-style\' });',
  '      styleEl.textContent = [',
  '        \'[data-show-all-router-views-scope] .routing-tabs,\',',
  '        \'[data-show-all-router-views-scope] .routing-card,\',',
  '        \'[data-show-all-router-views-scope] .routing-section,\',',
  '        \'[data-show-all-router-views-scope] .panel__tab,\',',
  '        \'[data-show-all-router-views-scope] [class*="routing-"],\',',
  '        \'[data-show-all-router-views-scope] [class*="tab--hidden"],\',',
  '        \'[data-show-all-router-views-scope] [class*="tab--disabled"],\',',
  '        \'[data-show-all-router-views-scope] [class*="tab--collapsed"] {\',',
  '        \'  display: revert !important;\',',
  '        \'  visibility: visible !important;\',',
  '        \'  opacity: 1 !important;\',',
  '        \'}\',',
  '        \'[data-show-all-router-views-scope] [aria-hidden="true"] {\',',
  '        \'  visibility: visible !important;\',',
  '        \'  opacity: 1 !important;\',',
  '        \'}\',',
  '      ].join(\'\\n\');',
  '      document.head.appendChild(styleEl);',
  '    }',
  '    if (root.getAttribute(\'data-show-all-router-views-scope\') !== \'1\') {',
  '      root.setAttribute(\'data-show-all-router-views-scope\', \'1\');',
  '    }',
  '    var walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT, null);',
  '    var node = walker.currentNode;',
  '    var touched = [];',
  '    while (node) {',
  '      if (isRouterSurface(node) && isElementHidden(node)) {',
  '        var ancestor = node;',
  '        while (ancestor && ancestor !== root) {',
  '          if (isElementHidden(ancestor)) {',
  '            touched.push(ancestor);',
  '            forceVisible(ancestor);',
  '          }',
  '          ancestor = ancestor.parentElement;',
  '        }',
  '        touched.push(node);',
  '        forceVisible(node);',
  '      }',
  '      node = walker.nextNode();',
  '    }',
  '    return touched.length;',
  '  }',
  '',
  '  function applyGateOverride() {',
  '    var routingRoot = qs(\'.container--lg\');',
  '    if (!routingRoot) return { ok: false, scope: null, forced: 0 };',
  '    var forced = applyVisibilityOverride(routingRoot);',
  '    var tabs = qs(\'.routing-tabs\', routingRoot);',
  '    if (tabs) {',
  '      tabs.setAttribute(\'data-show-all-router-views\', \'gates-flipped\');',
  '    }',
  '    return { ok: true, scope: routingRoot, forced: forced };',
  '  }',
  '',
  '  function findSolidOwner(root) {',
  '    if (!root) return null;',
  '    var node = root;',
  '    while (node && node !== document.body) {',
  '      var owner = node[\'$$Owner\'] || node[\'_$$_Owner\'] || null;',
  '      if (owner) return owner;',
  '      node = node.parentElement;',
  '    }',
  '    return null;',
  '  }',
  '',
  '  function ensureFab() {',
  '    var existing = qs(\'#show-all-router-views-fab\');',
  '    if (existing) return existing;',
  '    var fab = el(\'button\', {',
  '      id: \'show-all-router-views-fab\',',
  '      type: \'button\',',
  '      class: \'show-all-router-views__fab\',',
  '      \'aria-label\': \'Reveal all router views\',',
  '      title: \'Reveal all router views (show-all-router-views v\' + SCRIPT_VERSION + \')\',',
  '      dataset: { showAllRouterViews: \'fab\' },',
  '      style: {',
  '        position: \'fixed\',',
  '        right: \'24px\',',
  '        bottom: \'24px\',',
  '        zIndex: \'9999\',',
  '        padding: \'12px 18px\',',
  '        borderRadius: \'9999px\',',
  '        border: \'none\',',
  '        cursor: \'pointer\',',
  '        background: \'hsl(var(--foreground))\',',
  '        color: \'hsl(var(--background))\',',
  '        fontFamily: \'var(--font-family)\',',
  '        fontSize: \'var(--font-size-sm, 14px)\',',
  '        fontWeight: \'600\',',
  '        boxShadow: \'0 4px 14px rgba(0,0,0,0.2)\',',
  '      },',
  '      onclick: function () { openModal(); },',
  '    }, [\'Reveal all router views\']);',
  '    document.body.appendChild(fab);',
  '    return fab;',
  '  }',
  '',
  '  function closeModal() {',
  '    var overlay = qs(\'#show-all-router-views-modal\');',
  '    if (overlay) overlay.remove();',
  '  }',
  '',
  '  function openModal() {',
  '    var agentName = getAgentName();',
  '    if (!agentName) {',
  '      window.alert(\'show-all-router-views: not on a routing page\');',
  '      return;',
  '    }',
  '    if (qs(\'#show-all-router-views-modal\')) return;',
  '',
  '    var overlay = el(\'div\', {',
  '      id: \'show-all-router-views-modal\',',
  '      class: \'show-all-router-views__overlay\',',
  '      dataset: { showAllRouterViews: \'overlay\' },',
  '      style: {',
  '        position: \'fixed\',',
  '        inset: \'0\',',
  '        zIndex: \'10000\',',
  '        background: \'rgba(0,0,0,0.55)\',',
  '        display: \'flex\',',
  '        alignItems: \'center\',',
  '        justifyContent: \'center\',',
  '        padding: \'24px\',',
  '      },',
  '      onclick: function (e) { if (e.target === overlay) closeModal(); },',
  '    });',
  '',
  '    var card = el(\'div\', {',
  '      class: \'show-all-router-views__card\',',
  '      dataset: { showAllRouterViews: \'card\' },',
  '      style: {',
  '        background: \'hsl(var(--card))\',',
  '        color: \'hsl(var(--card-foreground, var(--foreground)))\',',
  '        borderRadius: \'12px\',',
  '        boxShadow: \'0 12px 40px rgba(0,0,0,0.3)\',',
  '        maxWidth: \'1100px\',',
  '        width: \'100%\',',
  '        maxHeight: \'85vh\',',
  '        display: \'flex\',',
  '        flexDirection: \'column\',',
  '        fontFamily: \'var(--font-family)\',',
  '      },',
  '      onclick: function (e) { e.stopPropagation(); },',
  '    });',
  '',
  '    var header = el(\'div\', {',
  '      style: {',
  '        display: \'flex\',',
  '        alignItems: \'center\',',
  '        justifyContent: \'space-between\',',
  '        padding: \'16px 20px\',',
  '        borderBottom: \'1px solid hsl(var(--border))\',',
  '        flexShrink: \'0\',',
  '      },',
  '    }, [',
  '      el(\'div\', null, [',
  '        el(\'h2\', {',
  '          style: {',
  '            margin: \'0\',',
  '            fontSize: \'var(--font-size-lg, 18px)\',',
  '            fontWeight: \'700\',',
  '            color: \'hsl(var(--foreground))\',',
  '          },',
  '        }, [\'All router views — \' + agentName]),',
  '        el(\'p\', {',
  '          style: {',
  '            margin: \'4px 0 0 0\',',
  '            fontSize: \'var(--font-size-xs, 12px)\',',
  '            color: \'hsl(var(--muted-foreground))\',',
  '          },',
  '        }, [',
  '          \'Every configured routing rule, including rows the upstream UI hides \',',
  '          \'via the deprecation gate. Click Delete to remove a row; the page will \',',
  '          \'re-fetch automatically. This audit does not auto-delete anything.\',',
  '        ]),',
  '      ]),',
  '      el(\'button\', {',
  '        type: \'button\',',
  '        \'aria-label\': \'Close\',',
  '        title: \'Close\',',
  '        style: {',
  '          background: \'transparent\',',
  '          border: \'none\',',
  '          fontSize: \'20px\',',
  '          cursor: \'pointer\',',
  '          color: \'hsl(var(--muted-foreground))\',',
  '          padding: \'0 8px\',',
  '        },',
  '        onclick: function () { closeModal(); },',
  '      }, [\'×\']),',
  '    ]);',
  '',
  '    var body = el(\'div\', {',
  '      id: \'show-all-router-views-body\',',
  '      style: {',
  '        padding: \'16px 20px\',',
  '        overflowY: \'auto\',',
  '        flex: \'1 1 auto\',',
  '      },',
  '    }, [',
  '      el(\'p\', {',
  '        style: { color: \'hsl(var(--muted-foreground))\', margin: \'8px 0\' },',
  '      }, [\'Loading all routing data…\']),',
  '    ]);',
  '',
  '    card.appendChild(header);',
  '    card.appendChild(body);',
  '    overlay.appendChild(card);',
  '    document.body.appendChild(overlay);',
  '',
  '    loadAllRoutingData(agentName).then(function (data) {',
  '      renderAuditBody(body, agentName, data);',
  '    }).catch(function (e) {',
  '      body.innerHTML = \'\';',
  '      body.appendChild(el(\'p\', {',
  '        style: { color: \'hsl(var(--destructive))\' },',
  '      }, [\'Failed to load routing data: \' + (e && e.message || e)]));',
  '    });',
  '  }',
  '',
  '  function routeLabel(route) {',
  '    if (!route) return \'— (auto) —\';',
  '    var provider = route.provider || \'?\';',
  '    var authType = route.authType ? \' / \' + route.authType : \'\';',
  '    var model = route.model || \'?\';',
  '    return provider + authType + \' :: \' + model;',
  '  }',
  '',
  '  function tierLabel(tier) {',
  '    if (!tier) return \'—\';',
  '    return tier + (tier === \'default\' ? \' (fallback for everything else)\' : \'\');',
  '  }',
  '',
  '  function formatBool(b) { return b ? \'true\' : \'false\'; }',
  '',
  '  function renderSection(title, rows, columns, deleter) {',
  '    var section = el(\'section\', {',
  '      style: { marginBottom: \'24px\' },',
  '      dataset: { showAllRouterViews: \'section\' },',
  '    });',
  '    section.appendChild(el(\'h3\', {',
  '      style: {',
  '        margin: \'0 0 8px 0\',',
  '        fontSize: \'var(--font-size-md, 15px)\',',
  '        fontWeight: \'600\',',
  '        color: \'hsl(var(--foreground))\',',
  '      },',
  '    }, [title + \' (\' + rows.length + \')\']));',
  '    if (rows.length === 0) {',
  '      section.appendChild(el(\'p\', {',
  '        style: {',
  '          color: \'hsl(var(--muted-foreground))\',',
  '          margin: \'0\',',
  '          fontSize: \'var(--font-size-sm, 14px)\',',
  '        },',
  '      }, [\'(no rows)\']));',
  '      return section;',
  '    }',
  '    var table = el(\'table\', {',
  '      style: {',
  '        width: \'100%\',',
  '        borderCollapse: \'collapse\',',
  '        fontSize: \'var(--font-size-xs, 12px)\',',
  '        color: \'hsl(var(--foreground))\',',
  '      },',
  '    });',
  '    var thead = el(\'thead\', null, [',
  '      el(\'tr\', null, columns.map(function (c) {',
  '        return el(\'th\', {',
  '          style: {',
  '            textAlign: \'left\',',
  '            padding: \'6px 8px\',',
  '            borderBottom: \'1px solid hsl(var(--border))\',',
  '            fontWeight: \'600\',',
  '            whiteSpace: \'nowrap\',',
  '          },',
  '        }, [c.label]);',
  '      }).concat([el(\'th\', { style: { width: \'1%\', whiteSpace: \'nowrap\' } }, [\'\'])])),',
  '    ]);',
  '    table.appendChild(thead);',
  '    var tbody = el(\'tbody\');',
  '    rows.forEach(function (row) {',
  '      var tr = el(\'tr\', { dataset: { showAllRouterViews: \'row\', rowId: row.id || row.category || row.tier || \'\' } });',
  '      columns.forEach(function (c) {',
  '        tr.appendChild(el(\'td\', {',
  '          style: {',
  '            padding: \'6px 8px\',',
  '            borderBottom: \'1px solid hsl(var(--border))\',',
  '            verticalAlign: \'top\',',
  '            whiteSpace: \'nowrap\',',
  '          },',
  '        }, [c.render ? c.render(row) : (row[c.key] === null || row[c.key] === undefined ? \'—\' : String(row[c.key]))]));',
  '      });',
  '      if (deleter) {',
  '        tr.appendChild(el(\'td\', {',
  '          style: { padding: \'6px 8px\', borderBottom: \'1px solid hsl(var(--border))\', whiteSpace: \'nowrap\' },',
  '        }, [',
  '          el(\'button\', {',
  '            type: \'button\',',
  '            style: {',
  '              padding: \'4px 10px\',',
  '              borderRadius: \'6px\',',
  '              border: \'1px solid hsl(var(--destructive))\',',
  '              background: \'transparent\',',
  '              color: \'hsl(var(--destructive))\',',
  '              cursor: \'pointer\',',
  '              fontSize: \'var(--font-size-xs, 12px)\',',
  '            },',
  '            onclick: function () {',
  '              if (!window.confirm(\'Delete this routing rule?\\n\\n\' + (row.id || row.category || row.tier || \'\'))) return;',
  '              deleter(row).then(function () {',
  '                tr.parentNode && tr.parentNode.removeChild(tr);',
  '                var h3 = section.querySelector(\'h3\');',
  '                if (h3) {',
  '                  var n = section.querySelectorAll(\'tbody tr\').length;',
  '                  h3.textContent = title + \' (\' + n + \')\';',
  '                }',
  '              }).catch(function (e) {',
  '                window.alert(\'Delete failed: \' + (e && e.message || e));',
  '              });',
  '            },',
  '          }, [\'Delete\']),',
  '        ]));',
  '      } else {',
  '        tr.appendChild(el(\'td\', { style: { padding: \'6px 8px\' } }, [\'\']));',
  '      }',
  '      tbody.appendChild(tr);',
  '    });',
  '    table.appendChild(tbody);',
  '    section.appendChild(table);',
  '    return section;',
  '  }',
  '',
  '  function renderAuditBody(body, agentName, data) {',
  '    body.innerHTML = \'\';',
  '',
  '    body.appendChild(el(\'p\', {',
  '      style: {',
  '        margin: \'0 0 16px 0\',',
  '        fontSize: \'var(--font-size-xs, 12px)\',',
  '        color: \'hsl(var(--muted-foreground))\',',
  '      },',
  '    }, [',
  '      \'Read-only audit. Showing every row from the public Manifest routing API for this agent. \',',
  '      \'Stale rows (e.g. override_route → model the agent no longer has, header_tier pointing to a deleted provider) \',',
  '      \'appear here even when the upstream UI hides them.\',',
  '    ]));',
  '',
  '    // Tiers (complexity + default)',
  '    var tierRows = [];',
  '    if (data.tiers && data.tiers.__error) {',
  '      body.appendChild(el(\'p\', { style: { color: \'hsl(var(--destructive))\' } },',
  '        [\'Tiers API error: \' + data.tiers.__error]));',
  '    } else {',
  '      tierRows = (data.tiers || []).map(function (t) {',
  '        return {',
  '          id: t.id,',
  '          tier: t.tier,',
  '          override_model: t.override_model || (t.override_route && t.override_route.model) || null,',
  '          auto_assigned_model: t.auto_assigned_model || (t.auto_assigned_route && t.auto_assigned_route.model) || null,',
  '          override_route: t.override_route || null,',
  '          response_mode: t.response_mode || null,',
  '          fallback_routes: t.fallback_routes || null,',
  '        };',
  '      });',
  '      body.appendChild(renderSection(',
  '        \'Complexity tiers (tier_assignments)\',',
  '        tierRows,',
  '        [',
  '          { label: \'Tier\', key: \'tier\', render: function (r) { return tierLabel(r.tier); } },',
  '          { label: \'Override model\', render: function (r) { return routeLabel(r.override_route) || (r.override_model || \'—\'); } },',
  '          { label: \'Auto-assigned\', render: function (r) { return r.auto_assigned_model || \'—\'; } },',
  '          { label: \'Response mode\', key: \'response_mode\' },',
  '          { label: \'Fallbacks\', render: function (r) {',
  '            return (r.fallback_routes || []).map(routeLabel).join(\' → \') || \'—\';',
  '          } },',
  '        ],',
  '        function (row) {',
  '          if (!row.id) throw new Error(\'tier row has no id (cannot DELETE)\');',
  '          return deleteJson(\'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/tiers/\' + encodeURIComponent(row.tier));',
  '        },',
  '      ));',
  '    }',
  '',
  '    // Specificity (task-specific)',
  '    if (data.specificity && data.specificity.__error) {',
  '      body.appendChild(el(\'p\', { style: { color: \'hsl(var(--destructive))\' } },',
  '        [\'Specificity API error: \' + data.specificity.__error]));',
  '    } else {',
  '      var specificityRows = (data.specificity || []).map(function (a) {',
  '        return {',
  '          id: a.id,',
  '          category: a.category,',
  '          is_active: a.is_active,',
  '          override_model: a.override_model || (a.override_route && a.override_route.model) || null,',
  '          override_route: a.override_route || null,',
  '          response_mode: a.response_mode || null,',
  '          fallback_routes: a.fallback_routes || null,',
  '        };',
  '      });',
  '      body.appendChild(renderSection(',
  '        \'Task-specific routing (specificity_assignments)\',',
  '        specificityRows,',
  '        [',
  '          { label: \'Category\', key: \'category\' },',
  '          { label: \'Active\', render: function (r) { return formatBool(r.is_active); } },',
  '          { label: \'Override model\', render: function (r) { return routeLabel(r.override_route) || (r.override_model || \'—\'); } },',
  '          { label: \'Response mode\', key: \'response_mode\' },',
  '          { label: \'Fallbacks\', render: function (r) {',
  '            return (r.fallback_routes || []).map(routeLabel).join(\' → \') || \'—\';',
  '          } },',
  '        ],',
  '        function (row) {',
  '          if (!row.category) throw new Error(\'specificity row has no category (cannot DELETE)\');',
  '          return deleteJson(\'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/specificity/\' + encodeURIComponent(row.category));',
  '        },',
  '      ));',
  '    }',
  '',
  '    // Header tiers (custom routing)',
  '    if (data.headerTiers && data.headerTiers.__error) {',
  '      body.appendChild(el(\'p\', { style: { color: \'hsl(var(--destructive))\' } },',
  '        [\'Header tiers API error: \' + data.headerTiers.__error]));',
  '    } else {',
  '      var headerTierRows = (data.headerTiers || []).map(function (t) {',
  '        return {',
  '          id: t.id,',
  '          name: t.name,',
  '          header_key: t.header_key,',
  '          header_value: t.header_value,',
  '          enabled: t.enabled,',
  '          sort_order: t.sort_order,',
  '          override_model: t.override_model || (t.override_route && t.override_route.model) || null,',
  '          override_route: t.override_route || null,',
  '          fallback_routes: t.fallback_routes || null,',
  '          response_mode: t.response_mode || null,',
  '        };',
  '      });',
  '      body.appendChild(renderSection(',
  '        \'Custom header-triggered routing (header_tiers)\',',
  '        headerTierRows,',
  '        [',
  '          { label: \'Name\', key: \'name\' },',
  '          { label: \'Header\', render: function (r) { return (r.header_key || \'\') + \': \' + (r.header_value || \'\'); } },',
  '          { label: \'Enabled\', render: function (r) { return formatBool(r.enabled); } },',
  '          { label: \'Sort\', key: \'sort_order\' },',
  '          { label: \'Override model\', render: function (r) { return routeLabel(r.override_route) || (r.override_model || \'—\'); } },',
  '          { label: \'Fallbacks\', render: function (r) {',
  '            return (r.fallback_routes || []).map(routeLabel).join(\' → \') || \'—\';',
  '          } },',
  '        ],',
  '        function (row) {',
  '          if (!row.id) throw new Error(\'header_tier row has no id (cannot DELETE)\');',
  '          return deleteJson(\'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/header-tiers/\' + encodeURIComponent(row.id));',
  '        },',
  '      ));',
  '    }',
  '',
  '    // Complexity status',
  '    if (data.complexity && data.complexity.__error) {',
  '      body.appendChild(el(\'p\', { style: { color: \'hsl(var(--destructive))\' } },',
  '        [\'Complexity status API error: \' + data.complexity.__error]));',
  '    } else {',
  '      body.appendChild(el(\'section\', { style: { marginTop: \'8px\' } }, [',
  '        el(\'h3\', {',
  '          style: {',
  '            margin: \'0 0 8px 0\',',
  '            fontSize: \'var(--font-size-md, 15px)\',',
  '            fontWeight: \'600\',',
  '            color: \'hsl(var(--foreground))\',',
  '          },',
  '        }, [\'Complexity routing status\']),',
  '        el(\'p\', {',
  '          style: { margin: \'0\', fontSize: \'var(--font-size-sm, 14px)\', color: \'hsl(var(--muted-foreground))\' },',
  '        }, [',
  '          \'enabled: \' + formatBool(!!(data.complexity && data.complexity.enabled)) + \'. \',',
  '          \'When false, the upstream UI hides the Complexity section; \',',
  '          \'rows above still show every configured tier so you can see what \',',
  '          \'would route if complexity was re-enabled.\',',
  '        ]),',
  '      ]));',
  '    }',
  '  }',
  '',
  '  function onRoutePage() {',
  '    return getAgentName() !== null;',
  '  }',
  '',
  '  function installOnCurrentRoute() {',
  '    if (!onRoutePage()) return;',
  '    applyGateOverride();',
  '    ensureFab();',
  '  }',
  '',
  '  function reapplyIfHidden() {',
  '    if (!onRoutePage()) return;',
  '    var routingRoot = qs(\'.container--lg\');',
  '    if (!routingRoot) return;',
  '    var walker = document.createTreeWalker(routingRoot, NodeFilter.SHOW_ELEMENT, null);',
  '    var node = walker.currentNode;',
  '    while (node) {',
  '      if (isRouterSurface(node) && isElementHidden(node)) {',
  '        applyGateOverride();',
  '        return;',
  '      }',
  '      node = walker.nextNode();',
  '    }',
  '  }',
  '',
  '  if (document.readyState === \'loading\') {',
  '    document.addEventListener(\'DOMContentLoaded\', installOnCurrentRoute, { once: true });',
  '  } else {',
  '    installOnCurrentRoute();',
  '  }',
  '',
  '  var lastPath = window.location.pathname;',
  '  var observer = new MutationObserver(function () {',
  '    var currentPath = window.location.pathname;',
  '    if (currentPath !== lastPath) {',
  '      lastPath = currentPath;',
  '      if (!onRoutePage()) {',
  '        var fab = qs(\'#show-all-router-views-fab\');',
  '        if (fab) fab.remove();',
  '        closeModal();',
  '        return;',
  '      }',
  '    }',
  '    if (onRoutePage()) {',
  '      installOnCurrentRoute();',
  '      reapplyIfHidden();',
  '    }',
  '  });',
  '  observer.observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: [\'class\', \'style\', \'hidden\', \'aria-hidden\'] });',
  '',
  '  window.addEventListener(\'popstate\', installOnCurrentRoute);',
  '',
  '  window.__manifestPluginsDashboardTransform.push({',
  '    id: PLUGIN_ID,',
  '    version: SCRIPT_VERSION,',
  '    install: installOnCurrentRoute,',
  '  });',
  '})();',
].join('\n');

export class ShowAllRouterViewsPlugin implements DashboardTransformPlugin {
  static readonly metadata: PluginMetadata = SHOW_ALL_ROUTER_VIEWS_PLUGIN_METADATA;

  getDashboardScript(): string {
    return SHOW_ALL_ROUTER_VIEWS_SCRIPT;
  }
}
