/**
 * CustomProviderModelCountFixPlugin — dashboard-transform plugin that
 * patches the "0 models" badge shown across FIVE Manifest dashboard
 * surfaces for custom Anthropic-compatible providers (e.g.
 * `claude-proxy`).
 *
 * ## Background — the upstream bug being worked around
 *
 * As of Manifest 6.x, the per-tenant provider listing endpoint at
 * `/api/v1/providers` (`tenant-providers.controller.ts::listProviders`)
 * computes `cached_model_count` by reading
 * `tenant_providers.cached_models.length`. For rows where
 * `provider = 'custom:<uuid>'` the `cached_models` JSON column is
 * `NULL`, so the upstream code (per the relevant controller) falls
 * back to `total_models: 0` and the dashboard renders `0 models` /
 * `0` in the Models column even though the proxy / custom provider
 * is fully reachable and routes traffic correctly.
 *
 * The router-picker endpoint (`/api/v1/routing/<agentName>/available-models`,
 * `ModelController::getAvailableModels`) DOES correctly return the
 * models for custom providers — it queries
 * `CustomProviderService.list(tenant_id)` and joins them in. So we
 * re-query that endpoint from the dashboard, group the results by
 * `provider_display_name` (which is only set on rows where
 * `provider.startsWith('custom:')`), and rewrite the rendered count.
 *
 * ## What this plugin touches
 *
 * Five surfaces:
 *
 * 1. **S1** — The per-agent Connections page
 *    (`/harnesses/<agentName>/providers`): the Models-column `<td>`
 *    of each row in the `table.data-table`.
 * 2. **S2** — The agent-list subscription note: the `<span>` adjacent
 *    to each row whose text matches `/models?:\s*\d+/i`. Rewrites
 *    only the numeric capture.
 * 3. **S3** — The ConnectionDetail page
 *    (`/providers/connections/<id>`): the `<span>` value node
 *    immediately following the `<span>Models:</span>` label. Uses the
 *    operator-configured model count for THIS connection (resolved via
 *    the connection-detail + custom-providers endpoints, i.e. the
 *    `custom_providers.models` column the Edit form writes); falls back
 *    to the routing-picker total with an "all custom providers"
 *    subtitle only when the per-connection lookup is unavailable.
 * 4. **S5** — The `/providers` connections-list page: per-row badge
 *    patch. Strict-fallback: if no stable selector for a row is
 *    found, that row is skipped silently (no marker, no wrong value).
 * 5. **S6** — The routing picker page
 *    (`/agents|harnesses/<name>/routing` or `/routing`): text nodes
 *    equal to `custom:<uuid>` are replaced with the provider display
 *    name from the same fetch. Label-only; no count badge is added.
 *
 * All patch sites append a single
 * `<small class="mwp-model-count-patch-note">` subtitle so the operator
 * can tell the value was patched client-side. Nothing else in the DOM
 * is mutated.
 *
 * ## Idempotency strategy
 *
 * The script tags each patched node with
 * `data-mwp-model-count-patched="true"` (S1/S3, legacy) or
 * `data-mp-count-fix="s2"|"s5"|"s6"` (new surfaces). MutationObserver
 * re-fires when upstream re-renders the table on data refresh; the
 * script skips already-tagged cells. Without this marker, every
 * upstream `r.refresh()` would trigger a re-patch and a parallel
 * re-fetch from `/available-models`.
 *
 * The script also registers one entry on
 * `window.__manifestPluginsDashboardTransform` and bails early if
 * an entry with `id === 'custom-provider-model-count-fix'` already
 * exists (the bundle re-evaluates on every page navigation since
 * the host serves it without cache headers).
 *
 * ## Why no upstream patch instead?
 *
 * The upstream fix would be a 5-line change in
 * `tenant-providers.controller.ts::listProviders` (swap
 * `cached_models.length` for `await customProviderRepo.models(uuid).length`)
 * plus `provider.controller.ts::99`. That fix is being tracked
 * upstream separately. Until it ships, this plugin delivers the
 * operator-visible UX result.
 *
 * ## Plugin kind
 *
 * `dashboard-transform`. The host concatenates every enabled
 * `dashboard-transform` plugin's `getDashboardScript()` output
 * into the single bundle served at
 * `/admin/dashboard-transform/all.js` and injects it via the
 * dashboard mount overlay.
 */
import type {
  DashboardTransformPlugin,
  PluginMetadata,
} from '../..';

export const CUSTOM_PROVIDER_MODEL_COUNT_FIX_PLUGIN_METADATA: PluginMetadata = Object.freeze({
  id: 'custom-provider-model-count-fix',
  name: 'Custom provider model count fix',
  version: '0.2.0',
  description:
    'Patches the "0 models" badge across five dashboard surfaces for ' +
    'custom Anthropic-compatible providers (e.g. claude-proxy): ' +
    '(S1) the per-agent Connections page Models column, ' +
    '(S2) the agent-list subscription note "models: N" span, ' +
    '(S3) the ConnectionDetail page "Models: 0" field (now scoped per-connection), ' +
    '(S5) the /providers connections-list badge, and ' +
    '(S6) the routing picker "custom:<uuid>" label. ' +
    'Re-queries /api/v1/routing/<agentName>/available-models and rewrites ' +
    'the rendered DOM count. Disabling this plugin restores the upstream ' +
    'display. Becomes a no-op once Manifest fixes the upstream ' +
    'cached_models.length fallback for custom providers.',
  kind: 'dashboard-transform',
});

/**
 * The browser-side script shipped to the dashboard. Self-contained:
 * no `import`/`require`, only `fetch`, `document`, and standard DOM
 * APIs (all available in the browser without a module loader).
 *
 * Shape: a single IIFE that:
 *   1. Bails if the dashboard-transform registry already has a
 *      `custom-provider-model-count-fix` entry (defensive: the bundle
 *      is re-evaluated on every page navigation).
 *   2. Detects whether the current page is one of five surfaces:
 *        - S1: the per-agent Connections page
 *          (`/harnesses/<agentName>/providers`, or the legacy alias
 *          `/agents/<agentName>/providers`),
 *        - S2: the agent-list subscription note (same URL as S1),
 *        - S3: the ConnectionDetail page
 *          (`/providers/connections/<id>`),
 *        - S5: the `/providers` connections-list page, or
 *        - S6: the routing picker page
 *          (`/agents|harnesses/<name>/routing` or `/routing`).
 *      On other pages the script is a no-op until the user navigates.
 *   3. Fetches the real model list once from
 *      `/api/v1/routing/<agentName>/available-models`, filters rows
 *      where `provider.startsWith('custom:')`, and groups them by
 *      `provider_display_name` (the human-readable name like
 *      'claude-proxy'). For pages without an agent in the URL
 *      (ConnectionDetail, /providers, /routing) it uses the built-in
 *      `Playground` agent — the picker returns ALL custom provider
 *      models regardless of agent.
 *   4a. S1: walks every row of `table.data-table`. If the provider-name
 *      `<td>` matches a custom provider's display name AND the Models
 *      `<td>` (the 4th cell) reads `0` or `-`, it rewrites the cell's
 *      text content to the real count (using `textContent`, never
 *      `innerHTML`) and appends a single
 *      `<small class="mwp-model-count-patch-note">` subtitle.
 *   4b. S2: in the same table walker, finds the adjacent `<span>`
 *      whose text matches `/models?:\s*\d+/i` and rewrites ONLY the
 *      numeric capture to the resolved count.
 *   4c. S3: walks every `<span>` looking for the literal `Models:`
 *      label, then patches the next-sibling `<span>` (the value node).
 *      Scoped per-connection: parses the connection ID from the URL and
 *      resolves the operator-configured model count for THAT connection
 *      via `fetchConfiguredModelCount` (connection-detail endpoint →
 *      `custom:<uuid>` → custom-providers list → `models.length`, the
 *      same data the Edit form writes). On success the subtitle is
 *      `'(patched: this connection)'`; otherwise the patcher falls back
 *      to the header-selector scope, then to the routing-picker total
 *      with subtitle
 *      `'(patched: all custom providers — scoping unavailable)'`.
 *   4d. S5: walks the `/providers` connections-list page, finds
 *      per-row provider cards, and patches the badge node with the
 *      provider's count. Strict-fallback: if no stable selector for
 *      a row is found, that row is skipped silently.
 *   4e. S6: walks text nodes under the routing-modal container (or
 *      document if modal not found) for nodes equal to
 *      `custom:<uuid>` and replaces them with the provider display
 *      name from the same fetch. Label-only; no count badge.
 *   5. Each patched node gets `data-mwp-model-count-patched="true"`
 *      (S1/S3, legacy) or `data-mp-count-fix="s2"|"s5"|"s6"` (new
 *      surfaces) so MutationObserver-triggered re-runs skip it.
 *   6. Installs a MutationObserver on `document.body` with
 *      `{childList: true, subtree: true}` so SPA navigation back to
 *      any patched page re-runs the patch on the fresh DOM. The
 *      observer fires on EVERY mutation while on a patched page
 *      (not just on path changes) — this fixes the timing bug where
 *      upstream re-renders between path changes were missed.
 */
export const CUSTOM_PROVIDER_MODEL_COUNT_FIX_SCRIPT: string = [
  '(function () {',
  '  \'use strict\';',
  '  if (typeof window === \'undefined\') return;',
  '',
  '  var PLUGIN_ID = \'custom-provider-model-count-fix\';',
  '  var SCRIPT_VERSION = \'0.2.0\';',
  '',
  '  // Combined-bundle registry. Every dashboard-transform plugin\'s IIFE',
  '  // appends one entry here; the host iterates the registry on',
  '  // DOMContentLoaded. We check it ourselves so a re-evaluation of',
  '  // the combined bundle (e.g. after SPA navigation) is a no-op.',
  '  if (window.__manifestPluginsDashboardTransform === undefined) {',
  '    window.__manifestPluginsDashboardTransform = [];',
  '  }',
  '  if (window.__manifestPluginsDashboardTransform.some(function (e) {',
  '    return e && e.id === PLUGIN_ID;',
  '  })) {',
  '    return;',
  '  }',
  '',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // URL detection',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // Five page shapes are in scope:',
  '  //',
  '  // 1. Agent-scoped Connections page (list view) — S1 + S2:',
  '  //      /harnesses/<agentName>/providers',
  '  //    (Manifest renamed /agents → /harnesses in the 6.x range. The',
  '  //     bundle we inspected redirects /agents/<name>/* → /harnesses/<name>/*,',
  '  //     but we match the literal path too in case the redirect is bypassed',
  '  //     in the iframe context.)',
  '  //',
  '  // 2. ConnectionDetail page (single-connection view) — S3:',
  '  //      /providers/connections/<id>',
  '  //    Renders fields as inline <span> pairs (label + value) instead',
  '  //    of a table row, so it needs a different DOM walker.',
  '  //',
  '  // 3. Providers connections-list page — S5:',
  '  //      /providers',
  '  //    Shows the connections list across all auth types. The routing-',
  '  //    picker endpoint requires a specific agent name, so we use the',
  '  //    built-in Playground agent for this page.',
  '  //',
  '  // 4. Routing picker page — S6:',
  '  //      /agents/<name>/routing  OR  /harnesses/<name>/routing  OR  /routing',
  '  //    The routing modal shows custom providers as "custom:<uuid>";',
  '  //    we relabel them to the provider display name.',
  '  //',
  '  // We do NOT match arbitrary pages — only the five known surfaces.',
  '  var CONNECTIONS_PATH_RE = /^\\/(?:agents|harnesses)\\/([^/]+)\\/providers\\/?$/;',
  '  var CONNECTION_DETAIL_PATH_RE = /^\\/providers\\/connections\\/([^/]+)\\/?$/;',
  '  var PROVIDERS_PATH_RE = /^\\/providers\\/?$/;',
  '  var ROUTING_PAGE_RE = /^\\/(?:agents|harnesses)\\/[^/]+\\/routing\\/?$/;',
  '  var ROUTING_PATH_RE = /^\\/(?:agents|harnesses)\\/([^/]+)\\/routing\\/?$/;',
  '  var ROUTING_ROOT_RE = /^\\/routing\\/?$/;',
  '',
  '  function getConnectionsAgentName() {',
  '    var m = window.location.pathname.match(CONNECTIONS_PATH_RE);',
  '    if (!m) return null;',
  '    try { return decodeURIComponent(m[1]); } catch (e) { return m[1]; }',
  '  }',
  '',
  '  // Returns the kind of page we are on so the patch router can pick',
  '  // the right DOM walker. The ConnectionDetail URL has no agent name',
  '  // in it; for that page we query the routing-picker endpoint with a',
  '  // built-in agent (Playground) because the picker returns ALL custom',
  '  // provider models regardless of which agent is named — verified',
  '  // against the live Manifest 6.x bundle.',
  '  function getCurrentPageKind() {',
  '    if (getConnectionsAgentName() !== null) return \'agent-list\';',
  '    if (CONNECTION_DETAIL_PATH_RE.test(window.location.pathname)) return \'connection-detail\';',
  '    if (PROVIDERS_PATH_RE.test(window.location.pathname)) return \'providers-list\';',
  '    if (ROUTING_PAGE_RE.test(window.location.pathname) || ROUTING_ROOT_RE.test(window.location.pathname)) return \'routing\';',
  '    return \'other\';',
  '  }',
  '',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // Small DOM helpers (kept inline so the IIFE stays self-contained)',
  '  // ─────────────────────────────────────────────────────────────────',
  '  function getText(el) {',
  '    // textContent never executes HTML; safe for user-influenced strings.',
  '    return el ? (el.textContent || \'\') : \'\';',
  '  }',
  '',
  '  function trim(s) { return (s || \'\').replace(/^\\s+|\\s+$/g, \'\'); }',
  '',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // API: fetch the routing-picker\'s available-models for the agent',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // The router picker endpoint already returns the right list — we',
  '  // only need to count rows where `provider.startsWith(\'custom:\')`.',
  '  // We group the rows by `provider_display_name` so the DOM walk can',
  '  // look up the count by the visible provider name on each row.',
  '  function fetchAvailableModels(agentName) {',
  '    var url = \'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/available-models\';',
  '    return fetch(url, { credentials: \'same-origin\' }).then(function (res) {',
  '      if (!res.ok) {',
  '        return res.text().then(function (body) {',
  '          throw new Error(\'GET \' + url + \' -> \' + res.status + \' \' + (body || \'\').slice(0, 200));',
  '        });',
  '      }',
  '      return res.json();',
  '    }).then(function (rows) {',
  '      var countsByName = Object.create(null);',
  '      var totalCustom = 0;',
  '      if (!Array.isArray(rows)) return { countsByName: countsByName, totalCustom: totalCustom };',
  '      for (var i = 0; i < rows.length; i += 1) {',
  '        var row = rows[i];',
  '        if (!row) continue;',
  '        // Filter: only custom:* provider rows.',
  '        if (typeof row.provider !== \'string\' || row.provider.indexOf(\'custom:\') !== 0) continue;',
  '        // Prefer the human-readable display name; fall back to a UUID',
  '        // slug when upstream drops the field (a known response-shape',
  '        // drift). Counting every custom row — not just the ones with a',
  '        // display name — keeps the patched total accurate even if',
  '        // upstream changes the response again.',
  '        var name = row.provider_display_name;',
  '        if (typeof name !== \'string\' || name.length === 0) {',
  '          var providerKey = typeof row.provider === \'string\' ? row.provider : \'\';',
  '          var uuid = providerKey.indexOf(\'custom:\') === 0 ? providerKey.slice(7) : providerKey;',
  '          // Truncate the UUID to 8 chars + ellipsis for the internal',
  '          // group key (the rendered count stays numeric; this key is',
  '          // only used for scoping).',
  '          name = uuid.length > 8 ? (providerKey.indexOf(\'custom:\') === 0 ? \'custom:\' : \'\') + uuid.slice(0, 8) + \'\\u2026\' : providerKey;',
  '        }',
  '        countsByName[name] = (countsByName[name] || 0) + 1;',
  '        totalCustom += 1;',
  '      }',
  '      return { countsByName: countsByName, totalCustom: totalCustom };',
  '    });',
  '  }',
  '',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // API: fetch the CONFIGURED model count for a single connection',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // The ConnectionDetail page URL carries the tenant_providers row id',
  '  // (`/providers/connections/<id>`). Two cheap config reads resolve the',
  '  // operator-configured model count for exactly that connection:',
  '  //',
  '  //   1. GET /api/v1/provider-analytics/connection-detail?connection_id=<id>',
  '  //      returns `connection.provider` — for custom providers this is',
  '  //      `custom:<uuid>` where the uuid is the custom_providers row id.',
  '  //   2. GET /api/v1/routing/Playground/custom-providers',
  '  //      returns one entry per custom provider with `id` and the',
  '  //      `models` array — the SAME array the Edit form writes to the',
  '  //      `custom_providers.models` JSON column. Its length is the',
  '  //      configured count the operator sees in the Edit form.',
  '  //',
  '  // This deliberately does NOT use the routing-picker',
  '  // `/available-models` count for the ConnectionDetail page: that',
  '  // endpoint aggregates models across ALL custom providers (plus any',
  '  // auto-discovered catalog rows), so it over-counts for a single',
  '  // connection. The picker count remains correct for the list views',
  '  // (S1/S2/S5) which need the routing view.',
  '  //',
  '  // Returns a Promise<number|null>: the configured count, or null when',
  '  // the connection is not a custom provider, the lookup fails, or the',
  '  // provider has no configured models — the caller then falls back to',
  '  // the legacy totalCustom behavior.',
  '  function fetchConfiguredModelCount(connectionId) {',
  '    if (!connectionId) return Promise.resolve(null);',
  '    var detailUrl = \'/api/v1/provider-analytics/connection-detail?connection_id=\' + encodeURIComponent(connectionId);',
  '    return fetch(detailUrl, { credentials: \'same-origin\' }).then(function (res) {',
  '      if (!res.ok) {',
  '        return res.text().then(function (body) {',
  '          throw new Error(\'GET \' + detailUrl + \' -> \' + res.status + \' \' + (body || \'\').slice(0, 200));',
  '        });',
  '      }',
  '      return res.json();',
  '    }).then(function (detail) {',
  '      var providerKey = detail && detail.connection && typeof detail.connection.provider === \'string\'',
  '        ? detail.connection.provider',
  '        : \'\';',
  '      if (providerKey.indexOf(\'custom:\') !== 0) return null;',
  '      var customId = providerKey.slice(7);',
  '      if (!customId) return null;',
  '      var listUrl = \'/api/v1/routing/Playground/custom-providers\';',
  '      return fetch(listUrl, { credentials: \'same-origin\' }).then(function (res) {',
  '        if (!res.ok) {',
  '          return res.text().then(function (body) {',
  '            throw new Error(\'GET \' + listUrl + \' -> \' + res.status + \' \' + (body || \'\').slice(0, 200));',
  '          });',
  '        }',
  '        return res.json();',
  '      }).then(function (providers) {',
  '        if (!Array.isArray(providers)) return null;',
  '        for (var i = 0; i < providers.length; i += 1) {',
  '          var cp = providers[i];',
  '          if (!cp || cp.id !== customId) continue;',
  '          if (!Array.isArray(cp.models)) return null;',
  '          return cp.models.length;',
  '        }',
  '        return null;',
  '      });',
  '    }).catch(function (err) {',
  '      // eslint-disable-next-line no-console',
  '      console.warn(\'[\' + PLUGIN_ID + \'] configured-models lookup failed:\', err && err.message || err);',
  '      return null;',
  '    });',
  '  }',
  '',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // API: map custom-provider display name → tenant_providers.id',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // The harness Providers page (`/harnesses/<agent>/providers`) renders',
  '  // each row\'s Provider cell with the CUSTOM PROVIDER\'s display name',
  '  // (e.g. `claude-proxy`), not the `custom:<uuid>` key. To resolve the',
  '  // operator-configured model count for each row we need the',
  '  // tenant_providers.id (the connectionId `fetchConfiguredModelCount`',
  '  // expects). Two cheap reads build the name → connectionId map:',
  '  //',
  '  //   1. GET /api/v1/routing/<agent>/providers',
  '  //      returns one entry per tenant_provider with `id` and',
  '  //      `provider` (the latter is `custom:<uuid>` for custom providers).',
  '  //   2. GET /api/v1/routing/<agent>/custom-providers',
  '  //      returns one entry per custom provider with `id` (the uuid) and',
  '  //      `name` (the display name shown in the table).',
  '  //',
  '  // Join: keep tenant_providers rows whose `provider` starts with',
  '  // `custom:`, strip the prefix to get the custom_providers.id, look up',
  '  // the matching custom_providers row, and emit `name → tp.id`.',
  '  //',
  '  // Returns a Promise<Object<string, string>>: an object keyed by the',
  '  // custom provider\'s display name whose values are tenant_providers.id',
  '  // strings. Returns an empty object on any failure — the caller then',
  '  // falls back to the picker count for every row.',
  '  function fetchCustomProviderConnectionsByDisplayName(agentName) {',
  '    if (!agentName) return Promise.resolve(Object.create(null));',
  '    var providersUrl = \'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/providers\';',
  '    var customUrl = \'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/custom-providers\';',
  '    var providersPromise = fetch(providersUrl, { credentials: \'same-origin\' }).then(function (res) {',
  '      if (!res.ok) {',
  '        return res.text().then(function (body) {',
  '          throw new Error(\'GET \' + providersUrl + \' -> \' + res.status + \' \' + (body || \'\').slice(0, 200));',
  '        });',
  '      }',
  '      return res.json();',
  '    });',
  '    var customPromise = fetch(customUrl, { credentials: \'same-origin\' }).then(function (res) {',
  '      if (!res.ok) {',
  '        return res.text().then(function (body) {',
  '          throw new Error(\'GET \' + customUrl + \' -> \' + res.status + \' \' + (body || \'\').slice(0, 200));',
  '        });',
  '      }',
  '      return res.json();',
  '    });',
  '    return Promise.all([providersPromise, customPromise]).then(function (results) {',
  '      var tenantProviders = results[0];',
  '      var customProviders = results[1];',
  '      var map = Object.create(null);',
  '      if (!Array.isArray(tenantProviders) || !Array.isArray(customProviders)) return map;',
  '      // Index custom providers by id for O(1) lookup.',
  '      var cpById = Object.create(null);',
  '      for (var i = 0; i < customProviders.length; i += 1) {',
  '        var cp = customProviders[i];',
  '        if (!cp || typeof cp.id !== \'string\') continue;',
  '        cpById[cp.id] = cp;',
  '      }',
  '      for (var j = 0; j < tenantProviders.length; j += 1) {',
  '        var tp = tenantProviders[j];',
  '        if (!tp || typeof tp.provider !== \'string\') continue;',
  '        if (tp.provider.indexOf(\'custom:\') !== 0) continue;',
  '        // Skip inactive connections — the row won\'t render for them.',
  '        if (tp.is_active === false) continue;',
  '        var customId = tp.provider.slice(7);',
  '        var match = cpById[customId];',
  '        if (!match || typeof match.name !== \'string\' || match.name.length === 0) continue;',
  '        if (typeof tp.id !== \'string\' || tp.id.length === 0) continue;',
  '        // First writer wins: if two tenant_providers rows point at the',
  '        // same custom provider (multi-key setup), the row we paint is',
  '        // whichever the upstream table rendered first. Either is fine',
  '        // — both resolve to the same configured models array.',
  '        if (!Object.prototype.hasOwnProperty.call(map, match.name)) {',
  '          map[match.name] = tp.id;',
  '        }',
  '      }',
  '      return map;',
  '    }).catch(function (err) {',
  '      // eslint-disable-next-line no-console',
  '      console.warn(\'[\' + PLUGIN_ID + \'] name→connectionId lookup failed:\', err && err.message || err);',
  '      return Object.create(null);',
  '    });',
  '  }',
  '',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // API: find custom providers connected on the harness but NOT enabled',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // The harness Providers page (`/harnesses/<agent>/providers`) lists',
  '  // every tenant_providers row whose `provider` starts with `custom:`.',
  '  // For the harness to actually route traffic through that provider,',
  '  // the row must also appear in the harness\'s `agent_enabled_providers`',
  '  // table — otherwise the routing-picker endpoint returns zero rows',
  '  // for the provider and the operator sees the "Models: –" symptom.',
  '  //',
  '  // This helper computes the set of custom providers that are CONNECTED',
  '  // (a tenant_providers row exists and `is_active !== false`) but NOT',
  '  // ENABLED (the tenant_providers.id is missing from the harness\'s',
  '  // `agent_enabled_providers`). Three cheap reads:',
  '  //',
  '  //   1. GET /api/v1/routing/<agent>/providers',
  '  //      → tenant_providers rows ({id, provider: \'custom:<uuid>\', is_active, ...})',
  '  //   2. GET /api/v1/agents/<agent>/enabled-providers',
  '  //      → { enabled: [tenant_provider_id, ...] }',
  '  //   3. GET /api/v1/routing/<agent>/custom-providers',
  '  //      → custom provider rows ({id, name, ...}) for display-name lookup',
  '  //',
  '  // Returns a Promise<{missingIds: string[], missingNames: string[]}|null>:',
  '  // the tenant_providers.id list (the ids the PUT endpoint expects) and',
  '  // the matching display names for the banner copy. Returns null on any',
  '  // failure so the caller can skip the banner without false positives.',
  '  function findMissingCustomProviderIds(agentName) {',
  '    if (!agentName) return Promise.resolve(null);',
  '    var providersUrl = \'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/providers\';',
  '    var enabledUrl = \'/api/v1/agents/\' + encodeURIComponent(agentName) + \'/enabled-providers\';',
  '    var customUrl = \'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/custom-providers\';',
  '    function getJson(url) {',
  '      return fetch(url, { credentials: \'same-origin\' }).then(function (res) {',
  '        if (!res.ok) {',
  '          return res.text().then(function (body) {',
  '            throw new Error(\'GET \' + url + \' -> \' + res.status + \' \' + (body || \'\').slice(0, 200));',
  '          });',
  '        }',
  '        return res.json();',
  '      });',
  '    }',
  '    return Promise.all([',
  '      getJson(providersUrl),',
  '      getJson(enabledUrl),',
  '      getJson(customUrl),',
  '    ]).then(function (results) {',
  '      var tenantProviders = results[0];',
  '      var enabledBody = results[1];',
  '      var customProviders = results[2];',
  '      if (!Array.isArray(tenantProviders)) return null;',
  '      if (!enabledBody || !Array.isArray(enabledBody.enabled)) return null;',
  '      if (!Array.isArray(customProviders)) return null;',
  '      // Index custom providers by id for O(1) display-name lookup.',
  '      var cpById = Object.create(null);',
  '      for (var i = 0; i < customProviders.length; i += 1) {',
  '        var cp = customProviders[i];',
  '        if (!cp || typeof cp.id !== \'string\') continue;',
  '        cpById[cp.id] = cp;',
  '      }',
  '      // Set of enabled tenant_provider ids for O(1) membership check.',
  '      var enabledSet = Object.create(null);',
  '      for (var e = 0; e < enabledBody.enabled.length; e += 1) {',
  '        var eid = enabledBody.enabled[e];',
  '        if (typeof eid === \'string\' && eid.length > 0) enabledSet[eid] = true;',
  '      }',
  '      var missingIds = [];',
  '      var missingNames = [];',
  '      for (var j = 0; j < tenantProviders.length; j += 1) {',
  '        var tp = tenantProviders[j];',
  '        if (!tp || typeof tp.provider !== \'string\') continue;',
  '        if (tp.provider.indexOf(\'custom:\') !== 0) continue;',
  '        // Skip inactive connections — the row won\'t render for them.',
  '        if (tp.is_active === false) continue;',
  '        if (typeof tp.id !== \'string\' || tp.id.length === 0) continue;',
  '        // Already enabled → nothing to do for this row.',
  '        if (Object.prototype.hasOwnProperty.call(enabledSet, tp.id)) continue;',
  '        var customId = tp.provider.slice(7);',
  '        var match = cpById[customId];',
  '        var displayName = match && typeof match.name === \'string\' && match.name.length > 0',
  '          ? match.name',
  '          : tp.provider;',
  '        missingIds.push(tp.id);',
  '        missingNames.push(displayName);',
  '      }',
  '      return { missingIds: missingIds, missingNames: missingNames };',
  '    }).catch(function (err) {',
  '      // eslint-disable-next-line no-console',
  '      console.warn(\'[\' + PLUGIN_ID + \'] missing-enabled-providers lookup failed:\', err && err.message || err);',
  '      return null;',
  '    });',
  '  }',
  '',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // Memoized provider label map (for S6 routing-picker relabel)',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // The routing picker shows custom providers as "custom:<uuid>".',
  '  // We build a map from that UUID string to the provider display name',
  '  // using the SAME fetch as the count data (no extra network requests).',
  '  // The map is memoized per-URL with a 30s TTL so repeated SPA',
  '  // navigations don\'t hammer the endpoint.',
  '  var labelMapCache = Object.create(null);',
  '  var LABEL_MAP_TTL_MS = 30000;',
  '',
  '  function resolveProviderLabelMap(agentName) {',
  '    var url = \'/api/v1/routing/\' + encodeURIComponent(agentName) + \'/available-models\';',
  '    var now = Date.now();',
  '    if (labelMapCache[url] && (now - labelMapCache[url].ts) < LABEL_MAP_TTL_MS) {',
  '      return Promise.resolve(labelMapCache[url].map);',
  '    }',
  '    return fetch(url, { credentials: \'same-origin\' }).then(function (res) {',
  '      if (!res.ok) {',
  '        return res.text().then(function (body) {',
  '          throw new Error(\'GET \' + url + \' -> \' + res.status + \' \' + (body || \'\').slice(0, 200));',
  '        });',
  '      }',
  '      return res.json();',
  '    }).then(function (rows) {',
  '      var map = Object.create(null);',
  '      if (!Array.isArray(rows)) return map;',
  '      for (var i = 0; i < rows.length; i += 1) {',
  '        var row = rows[i];',
  '        if (!row) continue;',
  '        if (typeof row.provider !== \'string\' || row.provider.indexOf(\'custom:\') !== 0) continue;',
  '        var name = row.provider_display_name;',
  '        if (typeof name !== \'string\' || name.length === 0) continue;',
  '        map[row.provider] = name;',
  '      }',
  '      labelMapCache[url] = { ts: now, map: map };',
  '      return map;',
  '    });',
  '  }',
  '',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // DOM patch',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // The Connections page renders a `table.data-table` whose columns',
  '  // are: [Provider, Type, Connection, Models, Actions]. The Models',
  '  // cell we patch is the 4th <td> in each <tr>. The 1st <td>',
  '  // contains the provider display name (the same string used as',
  '  // key in `countsByName`).',
  '  function patchTable(table, countsByName, configuredCountByName) {',
  '    if (!table || !countsByName) return;',
  '    var tbody = table.tBodies && table.tBodies[0];',
  '    if (!tbody) return;',
  '    var rows = tbody.rows;',
  '    if (!rows || rows.length === 0) return;',
  '    for (var i = 0; i < rows.length; i += 1) {',
  '      var tr = rows[i];',
  '      if (!tr || tr.cells.length < 4) continue;',
  '      var nameCell = tr.cells[0];',
  '      var modelsCell = tr.cells[3];',
  '      var providerName = trim(getText(nameCell));',
  '      if (!providerName) continue;',
  '      // Prefer the operator-configured count (custom_providers.models.length)',
  '      // when the caller resolved one for this row. This is the authoritative',
  '      // source on the harness Providers page because the routing-picker',
  '      // endpoint can return zero rows for a custom provider whose',
  '      // tenant_provider isn\'t wired into the harness\'s',
  '      // agent_enabled_providers (or whose cached_models is stale) even',
  '      // though the Edit form shows the configured models. The picker',
  '      // count is the fallback when the configured lookup fails.',
  '      var hasConfigured = configuredCountByName',
  '        && Object.prototype.hasOwnProperty.call(configuredCountByName, providerName)',
  '        && typeof configuredCountByName[providerName] === \'number\'',
  '        && configuredCountByName[providerName] > 0;',
  '      var pickerCount = Object.prototype.hasOwnProperty.call(countsByName, providerName)',
  '        ? countsByName[providerName]',
  '        : null;',
  '      var realCount = hasConfigured ? configuredCountByName[providerName] : pickerCount;',
  '      if (realCount === null || realCount <= 0) continue;',
  '      // Skip already-patched cells (idempotency). The dataset marker',
  '      // is set on the <td> so SPA-driven re-renders reuse it.',
  '      if (modelsCell && modelsCell.dataset && modelsCell.dataset.mwpModelCountPatched === \'true\') continue;',
  '      var currentText = trim(getText(modelsCell));',
  '      // Only patch when the rendered text is the broken state. The',
  '      // upstream renders `0` (number) or `-` (when nullish). If the',
  '      // cell already shows the real count we don\'t touch it.',
  '      if (currentText !== \'0\' && currentText !== \'-\' && currentText !== String(realCount)) {',
  '        // The cell shows something other than 0, -, or the real count.',
  '        // Conservative no-op: do not overwrite arbitrary text.',
  '        continue;',
  '      }',
  '      // Rewrite the displayed count via textContent (never innerHTML).',
  '      // We rebuild the cell rather than mutating text nodes so the',
  '      // subtitle sits on its own line beneath the count.',
  '      while (modelsCell.firstChild) {',
  '        modelsCell.removeChild(modelsCell.firstChild);',
  '      }',
  '      modelsCell.appendChild(document.createTextNode(String(realCount)));',
  '      // Append a single <small> subtitle so the operator knows the',
  '      // count was patched client-side. textContent for the message',
  '      // again — the string is a plugin constant, but defensive.',
  '      //',
  '      // Subtitle contract: when the configured count won we use the',
  '      // SAME subtitle as S3\'s success path — `(patched: this connection)`',
  '      // — because the value came from this connection\'s',
  '      // custom_providers.models column. When the picker count won we',
  '      // keep the legacy S1 subtitle `(patched by manifest-plugin)` so',
  '      // existing snapshots and operator docs don\'t drift.',
  '      var note = document.createElement(\'small\');',
  '      note.className = \'mwp-model-count-patch-note\';',
  '      // data-mwp- marker on the note itself for downstream tooling.',
  '      note.setAttribute(\'data-mwp-model-count-patched-note\', \'true\');',
  '      var subtitleText = hasConfigured ? \'(patched: this connection)\' : \'(patched by manifest-plugin)\';',
  '      note.appendChild(document.createTextNode(subtitleText));',
  '      modelsCell.appendChild(note);',
  '      modelsCell.dataset.mwpModelCountPatched = \'true\';',
  '    }',
  '  }',
  '',
  '  function findTable() {',
  '    // The Connections page has exactly one `table.data-table` for the',
  '    // providers list. We target by class since neither id nor data-testid',
  '    // is set (verified against AgentProviders-DkdPn0fN.js).',
  '    return document.querySelector(\'table.data-table\');',
  '  }',
  '',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // S2: Agent-list subscription note patcher',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // The agent-list page renders a subscription note near each row',
  '  // (e.g. "models: 0" or "model: 0"). We find the <span> whose text',
  '  // matches /models?:\s*\d+/i and rewrite ONLY the numeric capture',
  '  // to the resolved count. The marker is data-mp-count-fix="s2".',
  '  function patchAgentListSubscriptionNote(table, countsByName) {',
  '    if (!table || !countsByName) return;',
  '    var tbody = table.tBodies && table.tBodies[0];',
  '    if (!tbody) return;',
  '    var rows = tbody.rows;',
  '    if (!rows || rows.length === 0) return;',
  '    for (var i = 0; i < rows.length; i += 1) {',
  '      var tr = rows[i];',
  '      if (!tr || tr.cells.length < 1) continue;',
  '      var nameCell = tr.cells[0];',
  '      var providerName = trim(getText(nameCell));',
  '      if (!providerName) continue;',
  '      var realCount = Object.prototype.hasOwnProperty.call(countsByName, providerName)',
  '        ? countsByName[providerName]',
  '        : null;',
  '      if (realCount === null || realCount <= 0) continue;',
  '      // Look for a <span> inside the same row whose text matches',
  '      // /models?:\s*\d+/i. We search the whole row, not just one cell,',
  '      // because the note may be in a different <td> than the provider name.',
  '      var spans = tr.querySelectorAll(\'span\');',
  '      for (var j = 0; j < spans.length; j += 1) {',
  '        var span = spans[j];',
  '        if (!span) continue;',
  '        // Idempotency: skip if already patched.',
  '        if (span.dataset && span.dataset.mpCountFix === \'s2\') continue;',
  '        var text = trim(getText(span));',
  '        if (!/models?:\\s*\\d+/i.test(text)) continue;',
  '        // Rewrite only the numeric capture. The regex preserves the',
  '        // surrounding text (e.g. "models: " prefix).',
  '        var newText = text.replace(/(\\d+)/, String(realCount));',
  '        // Only patch when the rendered number is the broken state (0)',
  '        // or already matches the real count (idempotent re-run).',
  '        if (text === newText) continue;',
  '        span.textContent = newText;',
  '        span.dataset.mpCountFix = \'s2\';',
  '      }',
  '    }',
  '  }',
  '',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // S5: Provider connections-list badge patcher',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // The /providers page shows a connections list across all auth types.',
  '  // Each row is a provider card with a badge showing the model count.',
  '  // We walk each card, find the provider name + the badge node, and',
  '  // rewrite the badge text to the real count.',
  '  //',
  '  // STRICT-FALLBACK CONTRACT: if we cannot find a stable selector for',
  '  // a row at implementation time, we skip that row silently — no marker,',
  '  // no wrong value. This is intentional: painting a wrong count is worse',
  '  // than leaving the broken 0.',
  '  function patchProviderConnectionsBadge(countsByName) {',
  '    if (!countsByName) return;',
  '    // The connections list is rendered as a series of cards or rows.',
  '    // We look for elements that contain both a provider name and a',
  '    // numeric badge. The exact selector depends on the upstream bundle;',
  '    // we try a few known patterns and skip if none match.',
  '    //',
  '    // Pattern 1: table rows (same as S1 but on /providers)',
  '    var table = document.querySelector(\'table.data-table\');',
  '    if (table) {',
  '      var tbody = table.tBodies && table.tBodies[0];',
  '      if (tbody) {',
  '        var rows = tbody.rows;',
  '        for (var i = 0; i < rows.length; i += 1) {',
  '          var tr = rows[i];',
  '          if (!tr || tr.cells.length < 4) continue;',
  '          var nameCell = tr.cells[0];',
  '          var modelsCell = tr.cells[3];',
  '          var providerName = trim(getText(nameCell));',
  '          if (!providerName) continue;',
  '          var realCount = Object.prototype.hasOwnProperty.call(countsByName, providerName)',
  '            ? countsByName[providerName]',
  '            : null;',
  '          if (realCount === null || realCount <= 0) continue;',
  '          if (modelsCell && modelsCell.dataset && modelsCell.dataset.mpCountFix === \'s5\') continue;',
  '          var currentText = trim(getText(modelsCell));',
  '          if (currentText !== \'0\' && currentText !== \'-\' && currentText !== String(realCount)) continue;',
  '          while (modelsCell.firstChild) {',
  '            modelsCell.removeChild(modelsCell.firstChild);',
  '          }',
  '          modelsCell.appendChild(document.createTextNode(String(realCount)));',
  '          var note = document.createElement(\'small\');',
  '          note.className = \'mwp-model-count-patch-note\';',
  '          note.setAttribute(\'data-mwp-model-count-patched-note\', \'true\');',
  '          note.appendChild(document.createTextNode(\'(patched by manifest-plugin)\'));',
  '          modelsCell.appendChild(note);',
  '          modelsCell.dataset.mpCountFix = \'s5\';',
  '        }',
  '        return;',
  '      }',
  '    }',
  '    // Pattern 2: card-based layout (no table). We look for elements',
  '    // with a provider name and a sibling/count badge. If we can\'t find',
  '    // a stable selector, we skip silently (strict-fallback).',
  '    //',
  '    // The upstream bundle for /providers uses a card layout with',
  '    // provider name in a heading and a badge nearby. Without a stable',
  '    // data-testid or id, we cannot reliably target the badge — so we',
  '    // skip. This is the documented strict-fallback behavior.',
  '  }',
  '',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // S3: ConnectionDetail DOM patch (tightened to per-connection scope)',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // The ConnectionDetail page (`/providers/connections/<id>`) renders',
  '  // each field as an inline <span> pair:',
  '  //   <span>',
  '  //     <span style="font-weight:600;...">Models:</span>',
  '  //     \' \',',
  '  //     <span style="color:hsl(var(--muted-foreground))">{count}</span>',
  '  //   </span>',
  '  // (Verified against ConnectionDetail-nZtX-q3D.js in the Manifest 6.x',
  '  //  frontend bundle.) There is no table, no data-testid, and no',
  '  //  provider name on the same line — so we cannot use the countsByName',
  '  //  join directly. Instead we scope the count to THIS connection via',
  '  //  `fetchConfiguredModelCount(connectionId)`: the connection-detail',
  '  //  endpoint maps the URL id to `custom:<uuid>`, and the',
  '  //  custom-providers list endpoint exposes that provider\'s configured',
  '  //  `models` array (the same data the Edit form writes). When that',
  '  //  lookup succeeds we paint the configured count with subtitle',
  '  //  "(patched: this connection)". As a secondary scope we inspect the',
  '  //  page header for a stable provider-name selector matching a key in',
  '  //  countsByName. If neither resolves, we fall back to the TOTAL',
  '  //  custom-provider model count with subtitle',
  '  //  "(patched: all custom providers — scoping unavailable)".',
  '  //  Under no circumstances do we paint a wrong count.',
  '  function patchConnectionDetail(totalCustom, countsByName, configuredCount) {',
  '    var hasConfigured = typeof configuredCount === \'number\' && configuredCount > 0;',
  '    if (!hasConfigured && (typeof totalCustom !== \'number\' || totalCustom <= 0)) return;',
  '    // Parse the connection ID from the URL for scoping.',
  '    var connMatch = window.location.pathname.match(CONNECTION_DETAIL_PATH_RE);',
  '    var connectionId = connMatch ? connMatch[1] : null;',
  '    // Try to find a stable selector in the page header that exposes',
  '    // this connection\'s provider display name. The upstream bundle',
  '    // renders the provider name in a heading or breadcrumb near the',
  '    // top of the detail card. We look for the first <h1>, <h2>, or',
  '    // [data-provider-name] that matches a known custom provider.',
  '    var scopedProviderName = null;',
  '    var headerSelectors = [\'h1\', \'h2\', \'[data-provider-name]\', \'.provider-name\', \'.connection-provider\'];',
  '    for (var s = 0; s < headerSelectors.length; s += 1) {',
  '      var el = document.querySelector(headerSelectors[s]);',
  '      if (!el) continue;',
  '      var text = trim(getText(el));',
  '      if (!text) continue;',
  '      // Check if this text matches any known custom provider name.',
  '      for (var name in countsByName) {',
  '        if (Object.prototype.hasOwnProperty.call(countsByName, name) && text === name) {',
  '          scopedProviderName = name;',
  '          break;',
  '        }',
  '      }',
  '      if (scopedProviderName) break;',
  '    }',
  '    // Determine the count to display and the subtitle text. The',
  '    // configured-models count (from the custom_providers.models column',
  '    // via the custom-providers endpoint) is the authoritative source',
  '    // for this page — it matches what the operator sees in the Edit',
  '    // form. The routing-picker count over-counts because it aggregates',
  '    // every custom provider (and any auto-discovered rows), so it is',
  '    // only a fallback here.',
  '    var displayCount = totalCustom;',
  '    var subtitleText = \' (patched: all custom providers — scoping unavailable)\';',
  '    if (hasConfigured) {',
  '      displayCount = configuredCount;',
  '      subtitleText = \' (patched: this connection)\';',
  '    } else if (scopedProviderName !== null) {',
  '      displayCount = countsByName[scopedProviderName];',
  '      subtitleText = \' (patched: this connection)\';',
  '    }',
  '    // Walk every <span> in the document. The label span\'s text is',
  '    // exactly \'Models:\' (SolidJS renders it as a literal).',
  '    var spans = document.querySelectorAll(\'span\');',
  '    for (var i = 0; i < spans.length; i += 1) {',
  '      var label = spans[i];',
  '      if (!label) continue;',
  '      if (trim(getText(label)) !== \'Models:\') continue;',
  '      // The value span is the NEXT element sibling of the label span',
  '      // inside the same wrapper <span>. SolidJS inserts a text node',
  '      // (a single space) between them, so we use nextElementSibling',
  '      // to skip text nodes.',
  '      var valueSpan = label.nextElementSibling;',
  '      if (!valueSpan || valueSpan.tagName !== \'SPAN\') continue;',
  '      // Idempotency: skip if we already patched this value span.',
  '      if (valueSpan.dataset && valueSpan.dataset.mwpModelCountPatched === \'true\') continue;',
  '      var currentText = trim(getText(valueSpan));',
  '      // Only patch the broken state (0, -, or empty). If the upstream',
  '      // already shows the real count, leave it alone.',
  '      if (currentText !== \'0\' && currentText !== \'-\' && currentText !== \'\' && currentText !== String(displayCount)) {',
  '        continue;',
  '      }',
  '      // Rewrite the value via textContent (never innerHTML).',
  '      while (valueSpan.firstChild) {',
  '        valueSpan.removeChild(valueSpan.firstChild);',
  '      }',
  '      valueSpan.appendChild(document.createTextNode(String(displayCount)));',
  '      // Append the patch-note subtitle INSIDE the value span so it',
  '      // inherits the muted-foreground styling. The detail page layout',
  '      // is inline, so the note sits right after the count.',
  '      var note = document.createElement(\'small\');',
  '      note.className = \'mwp-model-count-patch-note\';',
  '      note.setAttribute(\'data-mwp-model-count-patched-note\', \'true\');',
  '      note.appendChild(document.createTextNode(subtitleText));',
  '      valueSpan.appendChild(note);',
  '      valueSpan.dataset.mwpModelCountPatched = \'true\';',
  '    }',
  '  }',
  '',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // S6: Routing picker relabel',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // The routing picker page shows custom providers as "custom:<uuid>".',
  '  // We walk all text nodes under the routing-modal container (or',
  '  // document if modal not found) and replace any text node whose',
  '  // content matches /^custom:[0-9a-f-]{36}$/ with the provider display',
  '  // name from the label map. If a key is missing in the map, we leave',
  '  // the upstream UUID label intact (NO-OP).',
  '  //',
  '  // This is label-only: we do NOT add a count badge inside the routing',
  '  // picker dropdown.',
  '  function patchRoutingPickerRelabel(nameMap) {',
  '    if (!nameMap) return;',
  '    // Find the routing-modal container. If not found, fall back to',
  '    // document.body so we still catch the labels.',
  '    var container = document.querySelector(\'.routing-modal\') || document.body;',
  '    if (!container) return;',
  '    // Walk all text nodes under the container.',
  '    var walker = document.createTreeWalker(',
  '      container,',
  '      NodeFilter.SHOW_TEXT,',
  '      null,',
  '      false',
  '    );',
  '    var node;',
  '    while ((node = walker.nextNode())) {',
  '      var text = node.textContent || \'\';',
  '      // Match exactly "custom:<uuid>" (36 chars after the colon).',
  '      if (!/^custom:[0-9a-f-]{36}$/.test(text)) continue;',
  '      // Look up the display name. If missing, leave the UUID intact.',
  '      var displayName = nameMap[text];',
  '      if (typeof displayName !== \'string\' || displayName.length === 0) continue;',
  '      // Replace the text node content.',
  '      node.textContent = displayName;',
  '      // Mark the parent element so we don\'t reprocess it.',
  '      var parent = node.parentElement;',
  '      if (parent && parent.dataset) {',
  '        parent.dataset.mpCountFix = \'s6\';',
  '      }',
  '    }',
  '  }',
  '',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // S7: Consent-gated banner for missing enabled-providers rows',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // When a custom provider has a tenant_providers row on the harness',
  '  // but is NOT in the harness\'s agent_enabled_providers table, the',
  '  // routing picker returns zero rows for it and the operator sees the',
  '  // broken "Models: –" state. The fix is a single PUT per missing id',
  '  // to /api/v1/agents/<agent>/enabled-providers/<tenant_provider_id>,',
  '  // which is idempotent (server-side .orIgnore()) and runs',
  '  // recalculateTiers on the backend.',
  '  //',
  '  // CONSENT CONTRACT: the plugin NEVER auto-enables. It paints a banner',
  '  // with two controls — "Enable missing providers" (fires the PUTs,',
  '  // sequentially, then reloads) and "Dismiss" (removes the banner from',
  '  // the DOM, in-memory only — no localStorage, no persistence). The',
  '  // operator can re-dismiss on the next page load if they want.',
  '  //',
  '  // Idempotency marker: data-mp-count-fix="s7" on the outer <div>.',
  '  // Buttons carry data-mp-action="enable" / "dismiss" for test',
  '  // selection. Built with createElement/appendChild/textContent only —',
  '  // never innerHTML.',
  '  function patchEnabledProvidersBanner(agentName, missingIds, missingNames) {',
  '    if (!agentName) return;',
  '    if (!Array.isArray(missingIds) || missingIds.length === 0) return;',
  '    if (!Array.isArray(missingNames)) missingNames = [];',
  '    // Idempotency: skip if a banner is already on the page.',
  '    if (document.querySelector(\'[data-mp-count-fix="s7"]\')) return;',
  '    var table = findTable();',
  '    if (!table) return;',
  '    // Build the banner element. DOM-construction uses createElement +',
  '    // appendChild + textContent exclusively — no innerHTML — so the',
  '    // provider names we render cannot inject markup.',
  '    var banner = document.createElement(\'div\');',
  '    banner.className = \'mwp-enabled-providers-banner\';',
  '    banner.setAttribute(\'data-mp-count-fix\', \'s7\');',
  '    banner.setAttribute(\'role\', \'status\');',
  '    var msg = document.createElement(\'p\');',
  '    var count = missingIds.length;',
  '    var plural = count === 1 ? \'provider isn\\\'t\' : \'providers aren\\\'t\';',
  '    var nameList = \'\';',
  '    if (missingNames.length > 0) {',
  '      nameList = \': \' + missingNames.join(\', \');',
  '    }',
  '    msg.textContent = count + \' custom \' + plural + \' enabled for this harness\'',
  '      + nameList + \'. Their models won\\\'t appear in routing.\';',
  '    banner.appendChild(msg);',
  '    var enableBtn = document.createElement(\'button\');',
  '    enableBtn.type = \'button\';',
  '    enableBtn.setAttribute(\'data-mp-action\', \'enable\');',
  '    enableBtn.textContent = \'Enable missing providers\';',
  '    banner.appendChild(enableBtn);',
  '    var dismissBtn = document.createElement(\'button\');',
  '    dismissBtn.type = \'button\';',
  '    dismissBtn.setAttribute(\'data-mp-action\', \'dismiss\');',
  '    dismissBtn.setAttribute(\'aria-label\', \'Dismiss\');',
  '    dismissBtn.textContent = \'Dismiss\';',
  '    banner.appendChild(dismissBtn);',
  '    // Insert BEFORE the table\'s parent element so the banner sits',
  '    // above the providers list. If the table has no parent (shouldn\'t',
  '    // happen — the table is in the DOM), skip silently.',
  '    var anchor = table.parentElement;',
  '    if (!anchor || !anchor.parentElement) return;',
  '    anchor.parentElement.insertBefore(banner, anchor);',
  '    // Wire the controls.',
  '    dismissBtn.addEventListener(\'click\', function () {',
  '      if (banner.parentElement) banner.parentElement.removeChild(banner);',
  '    });',
  '    enableBtn.addEventListener(\'click\', function () {',
  '      // Disable the button so double-clicks don\'t double-fire.',
  '      enableBtn.disabled = true;',
  '      // Fan out the PUTs SEQUENTIALLY (not Promise.all) — the backend',
  '      // runs recalculateTiers on every call, and parallel calls race.',
  '      var chain = Promise.resolve();',
  '      for (var i = 0; i < missingIds.length; i += 1) {',
  '        (function (tpId) {',
  '          chain = chain.then(function () {',
  '            var url = \'/api/v1/agents/\' + encodeURIComponent(agentName) + \'/enabled-providers/\' + encodeURIComponent(tpId);',
  '            return fetch(url, {',
  '              method: \'PUT\',',
  '              credentials: \'same-origin\',',
  '            }).then(function (res) {',
  '              if (!res.ok) {',
  '                return res.text().then(function (body) {',
  '                  throw new Error(\'PUT \' + url + \' -> \' + res.status + \' \' + (body || \'\').slice(0, 200));',
  '                });',
  '              }',
  '            });',
  '          });',
  '        })(missingIds[i]);',
  '      }',
  '      chain.then(function () {',
  '        // All PUTs succeeded — reload so the harness re-renders with',
  '        // the providers enabled and the routing picker populated.',
  '        window.location.reload();',
  '      }).catch(function (err) {',
  '        // eslint-disable-next-line no-console',
  '        console.warn(\'[\' + PLUGIN_ID + \'] enable-providers PUT failed:\', err && err.message || err);',
  '        // Keep the banner so the operator can retry; show an error.',
  '        msg.textContent = \'Failed to enable providers — check the console for details.\';',
  '        enableBtn.disabled = false;',
  '      });',
  '    });',
  '  }',
  '',
  '  function runPatch() {',
  '    var pageKind = getCurrentPageKind();',
  '    if (pageKind === \'other\') return;',
  '    // For the agent-list page we use the agent from the URL. For the',
  '    // connection-detail, providers-list, and routing pages there is no',
  '    // agent in the URL, so we use the built-in Playground agent — the',
  '    // routing-picker endpoint returns ALL custom provider models',
  '    // regardless of which agent is named, so the choice of agent only',
  '    // has to be one that exists.',
  '    var agentName = pageKind === \'agent-list\' ? getConnectionsAgentName() : \'Playground\';',
  '    if (!agentName) return;',
  '    fetchAvailableModels(agentName).then(function (data) {',
  '      // If upstream fixed the bug in the meantime, the broken state',
  '      // never renders and countsByName is empty — the patch is a',
  '      // no-op, which is the intended behavior.',
  '      if (!data || !data.countsByName) return;',
  '      if (pageKind === \'agent-list\') {',
  '        var table = findTable();',
  '        if (!table) return;',
  '        // The harness Providers page renders each custom-provider row',
  '        // with the custom provider\'s display name (e.g. `claude-proxy`)',
  '        // in the Provider cell. The routing-picker endpoint may return',
  '        // ZERO rows for that provider when its tenant_provider row',
  '        // isn\'t wired into the harness\'s agent_enabled_providers (or',
  '        // its cached_models is stale), which leaves the Models cell',
  '        // stuck at the broken `–`. To recover, resolve the operator-',
  '        // configured count (custom_providers.models.length, the same',
  '        // value the Edit form writes) per row and prefer it over the',
  '        // picker count. The picker count remains the fallback when',
  '        // the configured lookup fails.',
  '        //',
  '        // Subtitle contract: rows patched with the configured count',
  '        // use `(patched: this connection)` — the SAME subtitle as S3\'s',
  '        // success path — because the value came from this connection\'s',
  '        // custom_providers.models column. Rows that fall back to the',
  '        // picker count keep the legacy S1 subtitle',
  '        // `(patched by manifest-plugin)`.',
        '        fetchCustomProviderConnectionsByDisplayName(agentName).then(function (nameToConnectionId) {',
        '          // S7: in parallel with the configured-count fan-out, check',
        '          // whether any custom provider is connected but NOT enabled',
        '          // on this harness. If so, paint the consent-gated banner.',
        '          // The banner is independent of the table patch — even if',
        '          // the configured-count lookup succeeds, the operator still',
        '          // needs to know about the missing enabled-providers rows.',
        '          findMissingCustomProviderIds(agentName).then(function (missing) {',
        '            if (missing && missing.missingIds.length > 0) {',
        '              patchEnabledProvidersBanner(agentName, missing.missingIds, missing.missingNames);',
        '            }',
        '          }).catch(function (err) {',
        '            // eslint-disable-next-line no-console',
        '            console.warn(\'[\' + PLUGIN_ID + \'] missing-enabled-providers check failed:\', err && err.message || err);',
        '          });',
        '          var names = [];',
  '          for (var n in nameToConnectionId) {',
  '            if (Object.prototype.hasOwnProperty.call(nameToConnectionId, n)) names.push(n);',
  '          }',
  '          if (names.length === 0) {',
  '            // No custom providers connected on this harness — nothing',
  '            // to scope. Fall through with an empty configured map so',
  '            // patchTable uses picker counts only.',
  '            patchTable(table, data.countsByName, Object.create(null));',
  '            patchAgentListSubscriptionNote(table, data.countsByName);',
  '            return;',
  '          }',
  '          // Fan out one fetchConfiguredModelCount per unique',
  '          // connectionId, then build displayName → configuredCount.',
  '          // Duplicate connectionIds collapse into a single fetch via',
  '          // the seen-ids map.',
  '          var seenIds = Object.create(null);',
  '          var uniqueIds = [];',
  '          for (var k = 0; k < names.length; k += 1) {',
  '            var id = nameToConnectionId[names[k]];',
  '            if (!Object.prototype.hasOwnProperty.call(seenIds, id)) {',
  '              seenIds[id] = true;',
  '              uniqueIds.push(id);',
  '            }',
  '          }',
  '          Promise.all(uniqueIds.map(function (connId) {',
  '            return fetchConfiguredModelCount(connId);',
  '          })).then(function (counts) {',
  '            var configuredCountByName = Object.create(null);',
  '            for (var k2 = 0; k2 < names.length; k2 += 1) {',
  '              var nm = names[k2];',
  '              var cid = nameToConnectionId[nm];',
  '              var idx = -1;',
  '              for (var u = 0; u < uniqueIds.length; u += 1) {',
  '                if (uniqueIds[u] === cid) { idx = u; break; }',
  '              }',
  '              if (idx < 0) continue;',
  '              var c = counts[idx];',
  '              if (typeof c === \'number\' && c > 0) {',
  '                configuredCountByName[nm] = c;',
  '              }',
  '            }',
  '            patchTable(table, data.countsByName, configuredCountByName);',
  '            patchAgentListSubscriptionNote(table, data.countsByName);',
  '          }).catch(function (err) {',
  '            // eslint-disable-next-line no-console',
  '            console.warn(\'[\' + PLUGIN_ID + \'] configured-count fan-out failed:\', err && err.message || err);',
  '            patchTable(table, data.countsByName, Object.create(null));',
  '            patchAgentListSubscriptionNote(table, data.countsByName);',
  '          });',
  '        }).catch(function (err) {',
  '          // eslint-disable-next-line no-console',
  '          console.warn(\'[\' + PLUGIN_ID + \'] name→connectionId fetch failed:\', err && err.message || err);',
  '          patchTable(table, data.countsByName, Object.create(null));',
  '          patchAgentListSubscriptionNote(table, data.countsByName);',
  '        });',
  '      } else if (pageKind === \'connection-detail\') {',
  '        // ConnectionDetail: prefer the operator-configured model count',
  '        // for THIS connection (custom_providers.models via the',
  '        // connection-detail + custom-providers endpoints). The picker',
  '        // count (data.totalCustom) is only a fallback when the',
  '        // per-connection lookup fails.',
  '        var connMatch = window.location.pathname.match(CONNECTION_DETAIL_PATH_RE);',
  '        var connectionId = connMatch ? connMatch[1] : null;',
  '        fetchConfiguredModelCount(connectionId).then(function (configuredCount) {',
  '          patchConnectionDetail(data.totalCustom, data.countsByName, configuredCount);',
  '        });',
  '      } else if (pageKind === \'providers-list\') {',
  '        patchProviderConnectionsBadge(data.countsByName);',
  '      } else if (pageKind === \'routing\') {',
  '        // S6 uses the label map, not the count map. We resolve it',
  '        // from the same fetch (no extra network request).',
  '        resolveProviderLabelMap(agentName).then(function (nameMap) {',
  '          patchRoutingPickerRelabel(nameMap);',
  '        }).catch(function (err) {',
  '          // eslint-disable-next-line no-console',
  '          console.warn(\'[\' + PLUGIN_ID + \'] label-map fetch failed:\', err && err.message || err);',
  '        });',
  '      }',
  '    }).catch(function (err) {',
  '      // eslint-disable-next-line no-console',
  '      console.warn(\'[\' + PLUGIN_ID + \'] available-models fetch failed:\', err && err.message || err);',
  '    });',
  '  }',
  '',
  '  function onPatchedPage() {',
  '    return getCurrentPageKind() !== \'other\';',
  '  }',
  '',
  '  function installOnCurrentRoute() {',
  '    if (!onPatchedPage()) return;',
  '    runPatch();',
  '  }',
  '',
  '  // ─────────────────────────────────────────────────────────────────',
  '  // Lifecycle',
  '  // ─────────────────────────────────────────────────────────────────',
  '  if (document.readyState === \'loading\') {',
  '    document.addEventListener(\'DOMContentLoaded\', installOnCurrentRoute, { once: true });',
  '  } else {',
  '    installOnCurrentRoute();',
  '  }',
  '',
  '  // SPA navigation: re-mount when the path changes. MutationObserver',
  '  // watches `document.body` with `childList + subtree` only (no',
  '  // attributes filter) so the cost is negligible — fires only when',
  '  // the upstream router swaps the page container. The bundle itself',
  '  // is re-evaluated on every page navigation, so this observer is the',
  '  // belt-and-braces path: it ensures the patch re-applies even when',
  '  // the SPA soft-navigates without re-loading the bundle.',
  '  //',
  '  // TIMING BUG FIX: the old code short-circuited with',
  '  //   if (currentPath === lastPath) return;',
  '  // which meant the observer ONLY fired on path changes. If the',
  '  // upstream re-rendered the DOM between path changes (e.g. after',
  '  // a data refresh), the patch was missed. The new pattern updates',
  '  // the flag and ALWAYS calls installOnCurrentRoute() while on a',
  '  // patched page — matching the canonical pattern from',
  '  // show-all-router-views/plugin.ts:962-983.',
  '  var lastPath = window.location.pathname;',
  '  var observer = new MutationObserver(function () {',
  '    var currentPath = window.location.pathname;',
  '    if (currentPath !== lastPath) {',
  '      lastPath = currentPath;',
  '    }',
  '    if (onPatchedPage()) {',
  '      installOnCurrentRoute();',
  '    }',
  '  });',
  '  observer.observe(document.body, { childList: true, subtree: true });',
  '',
  '  window.addEventListener(\'popstate\', installOnCurrentRoute);',
  '',
  '  window.__manifestPluginsDashboardTransform.push({',
  '    id: PLUGIN_ID,',
  '    version: SCRIPT_VERSION,',
  '    install: installOnCurrentRoute,',
  '  });',
  '})();',
].join('\n');

export class CustomProviderModelCountFixPlugin implements DashboardTransformPlugin {
  static readonly metadata: PluginMetadata = CUSTOM_PROVIDER_MODEL_COUNT_FIX_PLUGIN_METADATA;

  getDashboardScript(): string {
    return CUSTOM_PROVIDER_MODEL_COUNT_FIX_SCRIPT;
  }
}
